export const selectData = {
  forSale: {
    category: [
      "Televisions",
      "Laptops and Desktop Computers",
      "iPad, Tablets & eReaders",
      "Phones",
      "Gaming Consoles and Accessories",
      "Home Theater Systems",
      "Kitchen Appliances",
      "Laundry Appliances",
      "Cleaning Appliances",
      "Heating, Cooling, and Air Quality",
      "Personal Care Appliances",
      "Miscellaneous Appliances",
      "Cameras and Camcorders",
      "Portable Music Players",
      "Wearable Technology",
      "Networking Devices",
      "Computer Components and Storage",
      "Office Equipment",
      "Security and Surveillance Equipment",
      "Audio Equipment",
      "Smart Home Devices",
      "Batteries and Power Supplies",
    ],
    Televisions: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $50",
        "$50 - $100",
        "$100 - $300",
        "$300 - $600",
        "$600 - $1,000",
        "Over $1,000",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      ScreenSize: [
        "12 inches",
        "15 inches",
        "19 inches",
        "20 inches",
        "22 inches",
        "24 inches",
        "28 inches",
        "32 inches",
        "36 inches",
        "40 inches",
        "42 inches",
        "43 inches",
        "48 inches",
        "49 inches",
        "50 inches",
        "55 inches",
        "58 inches",
        "60 inches",
        "65 inches",
        "70 inches",
        "75 inches",
        "80 inches",
        "82 inches",
        "85 inches",
        "88 inches",
        "90 inches",
        "93 inches",
        "98 inches",
        "100+",
      ],
      Resolution: [
        "Standard Definition (SD)",
        "High Definition (HD)",
        "Full HD (FHD)",
        "Ultra HD (UHD)/4K",
        "8K",
        "8K Ultra High Dynamic",
      ],
      Brand: [
        "Samsung",
        "LG",
        "Sony",
        "Panasonic",
        "Vizio",
        "TCL",
        "Hisense",
        "Philips",
        "Sharp",
        "Toshiba",
        "Skyworth",
        "Xiaomi",
        "BPL",
        "Westinghouse",
        "Element",
        "Sceptre",
        "Haier",
        "Onida",
        "AOC",
        "Noble Skiodo",
        "Thomson",
        "JVC",
        "RCA",
        "Sanus",
        "SYLVOX",
        "ONN",
        "ATYME",
        "Soulaca",
        "continuus",
        "Google",
        "Cello",
        "Amazon",
        "ZOSHING",
        "Ferguson",
        "SYLVOX",
        "August",
        "Digihome",
        "AKAI",
        "Sorandy",
        "Finlux",
        "ciciglow",
        "ASHATA",
        "Avtex",
        "eSTAR",
        "Denver",
        "aspure",
        "AFGZQ",
        "MSEURO",
        "Not Specified",
      ],
    },
    condition: ["New", "Refurbished", "Used", "For parts or not working"],
    color: [
      "Red",
      "Blue",
      "Green",
      "Yellow",
      "Purple",
      "Pink",
      "Orange",
      "Brown",
      "Black",
      "White",
      "Grey",
      "Gold",
      "Silver",
      "Navy blue",
      "Sky blue",
      "Lime green",
      "Teal",
      "Indigo",
      "Magenta",
      "Violet",
      "Khaki",
      "Salmon",
      "Crimson",
      "Lavender",
      "Plum",
      "Blue violet",
      "Olive",
      "Cyan",
      "Maroon",
      "Beige",
    ],
  },

  estate: {
    listing: ["Buying", "Renting", "Selling"],
    property: [
      "House",
      "Condominium",
      "Apartment/Flat",
      "Commericial",
      "Farmhouse",
      "Land",
      "Industrial",
      "Room",
      "Other",
    ],
    bedrooms: ["1", "2", "3", "4", "5+", "None"],
    bathrooms: ["1", "2", "3", "4", "5+", "None"],
    tenure: ["Freehold", "Leasehold", "Unknown"],
    propertyCondition: ["Excellent", "Good", "In need of repair"],
    key: [
      "Detached property",
      "Garage",
      "Double garage",
      "Private garden",
      "Communal garden",
      "Open plan living",
      "Gated community",
      "Balcony",
    ],
    nearest: [
      "Primary school",
      "Secondary school",
      "University",
      "Hospital",
      "Public transport",
      "Airport",
      "Restaurants & cafes",
      "Shopping centre",
      "Public park",
      "Beach",
      "None",
    ],
    facilities: [
      "Private parking",
      "Off road parking",
      "Internet",
      "Pets allowed",
      "Room service",
      "Shower",
      "Smoke alarms",
      "Fire extinguishers",
      "Washing machine",
      "Dishwasher",
      "Microwave",
      "Refrigerator",
      "Kitchenware",
      "Oven",
      "Dining area",
      "Seating Area",
      "Private entrance",
      "Heating",
      "Air conditioning",
      "Built-in wardrobes",
      "Fitten kitchen",
      "Disabled person facilities",
      "Private swimming pool",
      "Communal swimming pool",
      "Games Room",
      "Underfloor heating",
    ],
  },

  truck: {
    vehicleType: [
      "Aircraft",
      "Boats & Watercraft",
      "Cars",
      "Classic Cars",
      "Commericial Trucks",
      "Motorcycles",
      "RV & Motorhomes",
      "SUVs",
      "Trucks",
      "Utility & Work Trailers",
      "Vans",
      "Bikes",
      "Heavy Machinery",
      "Vehicles Wanted",
    ],
    saleType: ["Private Seller", "Trader"],
    condition: ["Brand new", "Used", "Accident damaged"],
    make: ["Make 1", "Make 2"],
    model: ["Model 1", "Model 2"],
    year: [
      ...[...new Array(new Date().getFullYear() - 1899)].map((_, index) => {
        return (
          index +
          new Date(Date.now()).getFullYear() -
          (new Date(Date.now()).getFullYear() - 1900)
        ).toString();
      }),
    ].reverse(),
    gearBox: ["Manual", "Automatic"],
    fualType: [
      "Gasoline",
      "Petrol",
      "Diesel",
      "Liquefied petroleum gas (LPG)",
      "Compressed Natural Gas (CNG)",
      "Micro Hybrid",
      "Mild Hybrid",
      "Mild Hybrid Electric Vehicle (MHEV)",
      "Hybrid Electric Vehicle (HEV)",
      "Plug-in Hybrid Electric Vehicle (PHEV)",
      "Battery Electric Vehicle (BEV)",
      "Hydrogen Fuel Cell Electric Vehicle (FCEV)",
      "Other",
    ],
    doors: ["1", "2", "3", "4", "5", "6", "7"],
    color: [
      "Beige",
      "Black",
      "Blue",
      "Bronze",
      "Brown",
      "Burgundy",
      "Gold",
      "Green",
      "Grey",
      "Indigo",
      "Magenta",
      "Maroon",
      "Multicolour",
      "Navy",
      "Orange",
      "Pink",
      "Purple",
      "Red",
      "Silver",
      "Turquoise",
      "White",
      "Yellow",
    ],
    bodyType: [
      "Hatchback",
      "Estate/Wagon",
      "SUV",
      "Saloon/Sedan",
      "Coupe",
      "Convertible",
      "Van/Minivan",
      "Truck/Pickup",
    ],
    seats: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19+",
    ],
  },
};
