export const selectData = {
  forSale: {
    category: [
      "Televisions",
      "Laptops and Desktop Computers",
      "iPad, Tablets & eReaders",
      "Phones",
      "Gaming Consoles and Accessories",
      "Home Theater Systems",
      "Kitchen Appliances",
      "Laundry Appliances",
      "Cleaning Appliances",
      "Heating, Cooling, and Air Quality",
      "Personal Care Appliances",
      "Miscellaneous Appliances",
      "Cameras and Camcorders",
      "Portable Music Players",
      "Wearable Technology",
      "Networking Devices",
      "Computer Components and Storage",
      "Office Equipment",
      "Security and Surveillance Equipment",
      "Audio Equipment",
      "Smart Home Devices",
      "Batteries and Power Supplies",
    ],
    Televisions: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $50",
        "$50 - $100",
        "$100 - $300",
        "$300 - $600",
        "$600 - $1,000",
        "Over $1,000",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      ScreenSize: [
        "12 inches",
        "15 inches",
        "19 inches",
        "20 inches",
        "22 inches",
        "24 inches",
        "28 inches",
        "32 inches",
        "36 inches",
        "40 inches",
        "42 inches",
        "43 inches",
        "48 inches",
        "49 inches",
        "50 inches",
        "55 inches",
        "58 inches",
        "60 inches",
        "65 inches",
        "70 inches",
        "75 inches",
        "80 inches",
        "82 inches",
        "85 inches",
        "88 inches",
        "90 inches",
        "93 inches",
        "98 inches",
        "100+",
      ],
      Resolution: [
        "Standard Definition (SD)",
        "High Definition (HD)",
        "Full HD (FHD)",
        "Ultra HD (UHD)/4K",
        "8K",
        "8K Ultra High Dynamic",
      ],
      Brand: [
        "Samsung",
        "LG",
        "Sony",
        "Panasonic",
        "Vizio",
        "TCL",
        "Hisense",
        "Philips",
        "Sharp",
        "Toshiba",
        "Skyworth",
        "Xiaomi",
        "BPL",
        "Westinghouse",
        "Element",
        "Sceptre",
        "Haier",
        "Onida",
        "AOC",
        "Noble Skiodo",
        "Thomson",
        "JVC",
        "RCA",
        "Sanus",
        "SYLVOX",
        "ONN",
        "ATYME",
        "Soulaca",
        "continuus",
        "Google",
        "Cello",
        "Amazon",
        "ZOSHING",
        "Ferguson",
        "SYLVOX",
        "August",
        "Digihome",
        "AKAI",
        "Sorandy",
        "Finlux",
        "ciciglow",
        "ASHATA",
        "Avtex",
        "eSTAR",
        "Denver",
        "aspure",
        "AFGZQ",
        "MSEURO",
        "Not Specified",
      ],
      SmartTV: ["Yes", "No"],
      Colour: [
        "Black",
        "Black and White",
        "White",
        "Wooden Housings",
        "Beige and Off-White",
        "Silver and Grey",
        "Silver",
        "Metallic Finishes",
        "Transparent",
        "Blue",
        "Green",
        "Purple",
        "Orange",
        "Pink",
        "Brown",
        "Gold",
        "Multicoloured",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Laptops: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $50",
        "$50 - $100",
        "$100 - $300",
        "$300 - $600",
        "$600 - $1,000",
        "Over $1,000",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: ["Laptops", "Desktop PCs", "2 - in - 1"],
      Brand: [
        "Apple",
        "Dell",
        "HP (Hewlett-Packard)",
        "Lenovo",
        "ASUS",
        "Acer",
        "Microsoft",
        "Samsung",
        "Toshiba",
        "Razer",
        "Huawei",
        "Gigabyte and Aorus",
        "Fujitsu",
        "LG",
        "System76",
        "Not Specified",
      ],
      ramSize: [
        "4 KB",
        "64 KB",
        "128 KB",
        "1 MB",
        "2 MB",
        "16 MB",
        "32 MB",
        "512 MB",
        "1 GB",
        "2 GB",
        "3 GB",
        "4 GB",
        "6 GB",
        "8 GB",
        "16 GB",
        "32 GB",
        "64 GB",
        "128 GB",
        "256 GB",
        "Not Specified",
      ],
      processor: [
        "8086/8088",
        "286",
        "386",
        "486",
        "i5",
        "Alder Lake",
        "AMD 10h",
        "AMD FX",
        "AMD K5",
        "AMD K6",
        "AMD K8",
        "AMD Ryzen",
        "AMD Ryzen Mobile",
        "AMD Sempron",
        "AMD Turion",
        "APL0098",
        "APL0278",
        "APL2298",
        "Apple A10 Fusion",
        "Apple A10X Fusion",
        "Apple A11 Bionic",
        "Apple A12",
        "Apple A12 Bionic",
        "Apple A12X Bionic",
        "Apple A12Z Bionic",
        "Apple A13 Bionic",
        "Apple A14 Bionic",
        "Apple A15 Bionic",
        "Apple A16 Bionic",
        "Apple A17 Pro",
        "Apple A4",
        "Apple A5",
        "Apple A5X",
        "Apple A6",
        "Apple A6X",
        "Apple A7",
        "Apple A8",
        "Apple A8X",
        "Apple A9",
        "Apple A9X",
        "Apple M1",
        "Apple M1 Max",
        "Apple M1 Pro",
        "Apple M1 Ultra",
        "Apple M2",
        "Apple M2 Max",
        "Apple M2 Pro",
        "Apple M2 Ultra",
        "Apple M7",
        "Apple M8",
        "ARM",
        "Athlon",
        "Athlon 64",
        "Athlon 64 X2",
        "Bobcat",
        "Clarkdale",
        "Coffee Lake",
        "Core 2 Duo",
        "Core i3",
        "i386",
        "i486",
        "i9",
        "Intel 4004",
        "Intel 8008",
        "Intel 80286",
        "Intel 8080",
        "Intel 8085",
        "Intel 8086",
        "Intel 8088",
        "Intel Atom",
        "Intel Celeron",
        "Intel Core",
        "Intel Core 2",
        "Intel Core 2 Quad",
        "Intel Core i3",
        "Intel Core i7",
        "Intel Core i9",
        "Intel Pentium",
        "Intel Xeon",
        "Itanium",
        "M series",
        "Micro-controller",
        "Motorola 68000",
        "NEC V30",
        "Opteron",
        "Pentium",
        "Pentium 4",
        "Pentium D",
        "Pentium II",
        "Pentium III",
        "Pentium M",
        "Pentium Pro",
        "PowerPC",
        "Sandy Bridge",
        "Sempron",
        "Skylake",
        "SPARC",
        "Steamroller",
        "Tiger Lake",
        "x86-64",
        "Yonah",
        "Zen",
        "Not Specified",
      ],
      ScreenSize: [
        "11.6 inches",
        "12 inches",
        "12.5 inches",
        "13.3 inches",
        "14 inches",
        "15.6 inches",
        "17 inches",
        "17.3 inches",
        "18.4 inches",
        "19 inches",
        "20 inches",
        "21 inches",
        "22 inches",
        "24 inches",
        "27 inches",
        "32 inches",
        "Ultrawide Monitors",
        "Not Specified",
      ],
      StorageCapacity: [
        "10 MB",
        "20 MB",
        "80 MB",
        "160 MB",
        "250 MB",
        "320 MB",
        "16 GB",
        "32 GB",
        "64 GB",
        "120 GB",
        "128 GB",
        "256 GB",
        "500 GB",
        "512 GB",
        "1 TB",
        "2 TB",
        "3 TB",
        "4 TB",
        "5 TB",
        "6 TB",
        "7 TB",
        "8 TB",
        "9 TB",
        "10 TB",
        "11 TB",
        "12 TB",
        "13 TB",
        "14 TB",
        "15 TB",
        "16 TB",
        "20 TB",
        "Not Specified",
      ],
      OperatingSystem: [
        "Windows 11 Home",
        "Windows 11 Pro",
        "Windows 10 Home",
        "Windows 10 Home",
        "Windows 10 Pro",
        "Windows 10 Pro",
        "Windows 10 in S mode",
        "Windows Legacy System",
        "Mac OS",
        "Chrome OS",
        "Linux",
        "MS-DOS",
        "CP/M",
        "Unix",
        "iOS",
        "Android",
        "BSD",
        "Solaris",
        "AmigaOS",
        "OS/2",
        "BeOS",
        "Atari TOS",
      ],
      Colour: [
        "Black",
        "White",
        "Stainless Steel/Silver",
        "Grey/Charcoal",
        "Space Grey",
        "Metallic Finishes",
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Orange",
        "Purple",
        "Gold",
        "Rose Gold",
        "Sandstone",
        "Pink",
        "Cream/Ivory",
        "Wood Finishes",
        "Transparent or Clear",
        "Patterned or Themed Designs",
        "Brushed Finishes",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
      BatteryLife: [
        "Up to 4 hours",
        "5 to 7 hours",
        "8 to 10 hours",
        "11 hours & above",
      ],
    },
    Ipad: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: ["iPads", "Tablets", "eReaders"],
      Brand: [
        "Apple",
        "Samsung",
        "Microsoft",
        "Lenovo",
        "Huawei",
        "Amazon",
        "Asus",
        "LG",
        "Google",
        "Acer",
        "Dell",
        "Sony",
        "HP",
        "Xiaomi",
        "TCL",
        "Realme",
        "Amazon Kindle",
        "Kobo",
        "Barnes & Noble Nook",
        "PocketBook",
        "Bookeen",
        "Onyx Boox",
        "Remarkable",
        "Honor",
        "Alcatel",
        "Doro",
        "Entity",
        "Nokia",
        "TCL",
        "Blackview",
        "ApoloSign",
        "BYYBUO",
        "acer",
        "YOBANSE",
        "Aheadthink",
        "UMIDIGI",
        "DOOGEE",
        "YESTEL",
        "ZZB",
        "CUPEISI",
        "NORTH BISON",
        "WXUNJA",
        "PRITOM",
        "COOPERS",
        "AOCWEI",
        "MEIZE",
        "Aiprotablet",
        "COLORROOM",
        "NOBKLEN",
        "BAKEN",
        "OUKITEL",
        "A DREAMER",
        "Ematic",
        "ZONKO",
        "ANTEMPER",
        "Contixo",
        "BYANDBY",
        "TOPELOTEK",
        "JUNINKE",
        "AWOW",
        "CWOWDEFU",
        "Mouikei",
        "MoKo",
        "MESWAO",
        "AZMXDVP",
        "Fintie",
        "BOOX",
        "NORTH BISON",
        "SUPERDUODUO",
        "PocketBook",
        "BOOX",
        "Meebook",
        "ASHATA",
        "ENJOY-UNIQUE",
        "Kadimendium",
        "TECHGEAR",
        "Berfea",
        "kwmobile",
        "Zcooooool",
        "Not Specified",
      ],
      ScreenSize: [
        "7 Inches",
        "7.9 Inches",
        "8 Inches",
        "8.9 Inches",
        "9 Inches",
        "9.9 Inches",
        "10 Inches",
        "10.2 Inches",
        "10.5 Inches",
        "10.9 Inches",
        "11 Inches",
        "11.9 Inches",
        "12 Inches",
        "12.9 Inches",
        "13 Inches",
        "13.9 Inches",
        "14 Inches & above",
        "Not Specified",
      ],
      Storage: [
        "10 MB",
        "20 MB",
        "80 MB",
        "160 MB",
        "250 MB",
        "320 MB",
        "16 GB",
        "32 GB",
        "64 GB",
        "120 GB",
        "128 GB",
        "256 GB",
        "500 GB",
        "512 GB",
        "1 TB",
        "2 TB",
        "3 TB",
        "4 TB",
        "5 TB",
        "6 TB",
        "7 TB",
        "8 TB",
        "9 TB",
        "10 TB",
        "11 TB",
        "12 TB",
        "13 TB",
        "14 TB",
        "15 TB",
        "16 TB",
        "20 TB",
        "Not Specified",
      ],
      Memory: [
        "4 KB",
        "64 KB",
        "128 KB",
        "1 MB",
        "2 MB",
        "16 MB",
        "32 MB",
        "256 MB",
        "512 MB",
        "1 GB",
        "2 GB",
        "3 GB",
        "4 GB",
        "5 GB",
        "6 GB",
        "8 GB",
        "16 GB",
        "32 GB",
        "64 GB",
        "128 GB",
        "256 GB",
        "Not Specified",
      ],
      BatteryLife: [
        "Up to 3 hours",
        "4 to 6 hours",
        "7 to 9 hours",
        "10 to 13 hours",
        "14 hours & above",
      ],
      Colour: [
        "Black",
        "White",
        "Stainless Steel/Silver",
        "Grey/Charcoal",
        "Space Grey",
        "Metallic Finishes",
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Orange",
        "Purple",
        "Gold",
        "Rose Gold",
        "Sandstone",
        "Pink",
        "Cream/Ivory",
        "Wood Finishes",
        "Transparent or Clear",
        "Patterned or Themed Designs",
        "Brushed Finishes",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    TheaterSystems: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      Type: [
        "Receivers",
        "Amplifiers",
        "Speakers",
        "Subwoofers",
        "Home Theater in a Box",
        "Soundbar Systems",
        "Wireless Home Theater Systems",
        "Virtual Surround Sound Systems",
        "Dolby Atmos Systems",
        "Custom-Built Systems",
        "Projectors and Screens",
        "Smart Home Theater Systems",
        "Compact Home Theater Systems",
        "Blu-ray/DVD Players",
        "Streaming Devices",
        "Not Specified",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Brand: [
        "Aluratek",
        "Acoustic Audio by Goldwood",
        "Ancable",
        "Arcam",
        "AudioQuest",
        "Auna",
        "Azatom",
        "Best Buy Brands",
        "Bobtot",
        "Bose",
        "Cambridge Audio",
        "Definitive Technology",
        "Denon",
        "Edifier",
        "Epson",
        "Fenton",
        "Harman Kardon",
        "Herdio",
        "Hisense",
        "Innovative Technology",
        "Insignia",
        "JBL",
        "Kaleidescape",
        "Klipsch",
        "Larksound",
        "LG",
        "Logitech",
        "Majority",
        "Marantz",
        "MartinLogan",
        "Monitor Audio",
        "NAD",
        "Nakamichi",
        "Onkyo",
        "Panasonic",
        "Philips",
        "Pioneer",
        "Pioneer Elite",
        "Polk Audio",
        "PowBuzz",
        "Puxinat",
        "Pyle",
        "Riowois",
        "Rocketfish",
        "Rockville",
        "Roku",
        "Saiyin",
        "Samsung",
        "Sanus",
        "Sharp",
        "Sonos",
        "Sony",
        "SunBriteTV",
        "TCL",
        "Ulimea",
        "Vizio",
        "Yamaha",
        "Zeerkeer",
        "Not Specified",
      ],
      Features: [
        "3-Chip Technology",
        "3D Blu-ray player",
        "4K UHD Playback",
        "4K UHD Video Pass Through",
        "4K Ultra HD",
        "A/B Switching",
        "App Compatible",
        "Auto Calibration",
        "Bluetooth",
        "Bridgeable",
        "Built-In Speakers",
        "CD Player",
        "Closed Captioning",
        "Digital Display",
        "Digital Keystone Correction",
        "Digital Tuner",
        "Digital Zoom Capability",
        "Dolby Atmos",
        "Enclosed",
        "ENERGY STAR Certified",
        "Equalizer",
        "HD Radio Tuner",
        "HDR Video Pass Through",
        "Headphone Jack",
        "High Dynamic Range (HDR)",
        "Integrated Amplifier",
        "Integrated Mount",
        "Integrated Speaker(s)",
        "Line-Level Inputs",
        "Mountable",
        "Multiroom Capability",
        "Pairing Technology",
        "Phono Input",
        "Plug-In",
        "Preamp Outputs",
        "Radio Tuner",
        "Remote Control Included",
        "Satellite Radio Tuner",
        "Separate Subwoofer Included",
        "Smart Capable",
        "Speaker(s) Included",
        "Text-To-Speech",
        "TV Tuner",
        "Wall Mountable",
        "Weather Resistant",
        "Wireless Connectivity",
        "Wireless Subwoofer Connectivity",
        "Mono",
        "Stereo",
        "Surround",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Kitchen: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      Type: [
        "Refrigerators and Freezers",
        "Ovens",
        "Stoves and Cooktops",
        "Range Hoods & Ventilation Systems",
        "Dishwashers",
        "Coffee Makers",
        "Blenders",
        "Food Processors",
        "Toasters & Oaster Ovens",
        "Kettles",
        "Rice Cookers",
        "Slow Cookers",
        "Juicers",
        "Electric Grills & Griddles",
        "Bread Makers",
        "Deep Fryers",
        "Sous Vide Machines",
        "Ice Cream Makers",
        "Wine Coolers & Cellars",
        "Indoor Herb Gardens",
        "Not Specified",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Brand: [
        "AIEVE",
        "Aigostar",
        "Argos Home",
        "Aisaving",
        "Albert Austin",
        "American Originals",
        "AVF",
        "AMOAMI",
        "Beko",
        "BELLA",
        "Berglander",
        "BLACK+DECKER",
        "BLACK+DECKER",
        "Bosch",
        "Bona",
        "Bush",
        "Brifit",
        "Braun",
        "Breville",
        "CANDY",
        "Chefman",
        "CHWARES",
        "COMFEE'",
        "COOK WITH COLOR",
        "Chill Factor",
        "Cooks Professional",
        "Cookworks",
        "COSORI",
        "Country Kitchen",
        "Krups",
        "Crock-Pot",
        "Cuisinart",
        "Drew & Cole",
        "Dualit",
        "DASH",
        "Dulce Gusto",
        "Dreo",
        "DeLonghi",
        "Elite Gourmet",
        "Ecoflow",
        "Farberware",
        "fullstar",
        "GE",
        "George Foreman",
        "GILES & POSNER",
        "Godboat",
        "Gorilla Grip",
        "GreenLife",
        "HADEN",
        "Hamilton Beach",
        "Hotpoint",
        "Hicoosee",
        "Holstein Housewares",
        "Home Hero",
        "Hisense",
        "Hoover",
        "Instant Pot",
        "Keurig",
        "Karcher",
        "KitchenAid",
        "Kenwood",
        "LG",
        "JML",
        "Laura Ashley",
        "Lavazza",
        "M MCIRCO",
        "MAIPOR",
        "Mattitude",
        "Magimix",
        "Masha",
        "Melitta",
        "Miele",
        "Morphy Richards",
        "Mueller Austria",
        "niffgaff",
        "Neff",
        "Ninja",
        "NINJA",
        "Nescafe",
        "Nostalgia",
        "Nutribullet",
        "Nespresso",
        "Nuwave",
        "Pyle",
        "Quest",
        "Philips",
        "Power XL",
        "Progress",
        "PerfectDraft",
        "Russell Hobbs",
        "Panasonic",
        "Salter",
        "Sage",
        "Samsung",
        "sangcon",
        "Sharp",
        "Slush Puppie",
        "Swan",
        "Smeg",
        "SHUNSHI",
        "sodastream",
        "Siemens",
        "Tassimo",
        "TOKIT",
        "Tower",
        "Tefal",
        "Umite Chef",
        "Vitamix",
        "VIVOHOME",
        "Walfos",
        "Wipro",
        "Zulay Kitchen",
        "Scotch-Brite",
        "LOSUY",
        "YKYI",
        "Russell Hobbs",
        "Vango",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Laundry: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within  30 miles",
        "Within  50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      Type: [
        "Washing Machines",
        "Dryers",
        "Ironing Boards & Irons",
        "Steamers",
        "Sewing Machines",
        "Not Specified",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Brands: [
        "Hoover",
        "Hotpoint",
        "Bush",
        "Samsung",
        "Beko",
        "Candy",
        "Bosch",
        "Tefal",
        "Indesit",
        "LG",
        "Russel Hobbs",
        "Haier",
        "Phillips",
        "Morphy Richards",
        "Hisense",
        "Tower",
        "Miele",
        "Breville",
        "Braun",
        "Steamworks",
        "Smeg",
        "Beldrey",
        "JML",
        "BLACK+DECKER",
        "Pyle",
        "COMFEE",
        "Hoover",
        "Bosch",
        "Electrolux",
        "Whirlpool",
        "GE",
        "Insignia",
        "GE Profile",
        "Maytag",
        "Amana",
        "Frigidaire",
        "Fisher & Paykel",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Cleaning: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      Type: [
        "Vacuum Cleaners",
        "Carpet Cleaners",
        "Steam Cleaners",
        "Air Purifiers",
        "Dehumidifiers",
        "Humidifiers",
        "Not Specified",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Brands: [
        "Bush",
        "Beko",
        "Vax",
        "Smeg",
        "Bissell",
        "Indesit",
        "Shark",
        "Hisense",
        "Dyson",
        "Hotpoint",
        "Leisure",
        "Rangemaster",
        "Philips",
        "Russell Hobbs",
        "Bona",
        "Bosch",
        "Neff",
        "Belling",
        "Stoves",
        "H20",
        "Karcher",
        "New World",
        "Samsung",
        "Henry",
        "Ninja",
        "Rug Doctor",
        "Sage",
        "Siemens",
        "Tefal",
        "Eufy",
        "Scotch-Brite",
        "LOSUY",
        "YKYI",
        "Hoover",
        "Bissell",
        "Miele",
        "Shark",
        "iRobot",
        "Electrolux",
        "LG",
        "Samsung",
        "Eureka",
        "Black+Decker",
        "Tineco",
        "Vax",
        "Karcher",
        "Neato Robotics",
        "Ecovacs",
        "Panasonic",
        "Bosch",
        "Rowenta",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Heating: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      Type: [
        "Air Conditioners",
        "Fans",
        "Heaters",
        "Thermostats",
        "Air Filters",
        "Not Specified",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Brands: [
        "Challenge",
        "Argos Home",
        "Dyson",
        "Habitat",
        "Duux",
        "Princess",
        "Meaco",
        "Honeywell",
        "Vicks",
        "Delonghi",
        "Dimplex",
        "Philips",
        "Midea",
        "Beldray",
        "Cookworks",
        "Salter",
        "Tower",
        "Alen",
        "Amana",
        "Amaze Heaters",
        "Ameriwood Home",
        "Arctic Wind",
        "AuxAC",
        "Barska",
        "Blueair",
        "Boneco",
        "CRANE",
        "Danby",
        "De'Longhi",
        "Dreo",
        "Emerson Quiet Kool",
        "Envion",
        "Freonic",
        "Frigidaire",
        "GE",
        "GE Profile",
        "GeoSmart Pro",
        "GermGuardian",
        "Gree",
        "Heat Storm",
        "HoMedics",
        "Honeywell",
        "Honeywell Home",
        "iBaby",
        "Ingenuity",
        "JHS",
        "Keystone",
        "KingHome",
        "Kyvol",
        "Lasko",
        "LG",
        "Lifesmart",
        "Molekule",
        "Napoleon",
        "NewAir",
        "Pure Enrichment",
        "PureGuardian",
        "RCA",
        "Sharp",
        "Sharper Image",
        "SPT",
        "Sunpentown",
        "TCL",
        "TORRAS",
        "uHoo",
        "Vornado",
        "Vornadobaby",
        "Westinghouse",
        "Whirlpool",
        "Whynter",
        "WINIX",
        "Woozoo",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    PersonalCare: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      Type: [
        "Hair Dryers",
        "Hair Straighteners & Curlers",
        "Electric Toothbrushes",
        "Shavers & Trimmers",
        "Massagers",
        "Not Specified",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Brands: [
        "Amazon Basics",
        "Andis",
        "BaByliss",
        "BaBylissPRO",
        "baKblade",
        "beseloa",
        "BIC",
        "Braun",
        "Braun",
        "Brightup",
        "CIBITA",
        "COSANO",
        "Dollar Shave Club",
        "DreamGenius",
        "FEIMUOSI",
        "Freedom Grooming",
        "GAMMA+",
        "Gillette",
        "Gillette Venus",
        "Hai",
        "Handsomeface",
        "Hatteker",
        "HIDRUO",
        "HoMedics",
        "iBaby",
        "INTUITION",
        "IWEEL",
        "JIAABCHOMO",
        "KEMEI",
        "kensen",
        "King C. Gillette",
        "MANSCAPED",
        "MAX-T",
        "MERIDIAN",
        "MICHAEL TODD BEAUTY",
        "Neialla",
        "Norelco",
        "NutriBullet",
        "Panasonic",
        "Philips",
        "Philips Beauty",
        "PIPPIXIA",
        "PMD Beauty",
        "PRITECH",
        "Remington",
        "ROAMAN",
        "Schick",
        "Schick Hydro Silk",
        "Sejoy",
        "Sharper Image",
        "Skull Shaver",
        "Solawave",
        "Styleader",
        "Supreme Trimmer",
        "SUPRENT",
        "SweetLF",
        "The Cut Buddy",
        "Tinkle",
        "Tweezerman",
        "Ufree",
        "Vanity Planet",
        "VGR",
        "VOYOR",
        "WAHL",
        "Xtreme Personal Care",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Miscellaneous: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      Type: [
        "Water Heaters",
        "Home Security Systems",
        "Smart Home Devices",
        "Battery Chargers & Power Supplies",
        "Garbage Disposals",
        "Not Listed",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Camera: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Brands: [
        "Agfaphoto",
        "AKASO",
        "Alpen Optics",
        "Aluratek",
        "Apple",
        "Arlo",
        "Arozzi",
        "Aura",
        "Autel Robotics",
        "Barbie",
        "Barska",
        "Best Buy Brands",
        "Blink",
        "Blue Microphones",
        "Bower",
        "BOYA",
        "Brakeburn",
        "Bresser",
        "Canon",
        "Celestron",
        "Chad Valley",
        "Contixo",
        "Digipower",
        "Discovery",
        "DJI",
        "Doro",
        "Duracell",
        "Ekids",
        "Elgato",
        "Endust",
        "Energizer",
        "Eufy Security",
        "EXO Drones",
        "Explore One",
        "Ezviz",
        "Fugifilm",
        "Fujinon",
        "Garmin",
        "Google Nest",
        "GoPro",
        "Honor",
        "HP",
        "Insignia",
        "Insta360",
        "Insta360",
        "Instax",
        "IOGEAR",
        "Joby",
        "Juice",
        "Kodak",
        "Kodak Pixpro",
        "Lastolite",
        "Lego",
        "Lenovo",
        "Lenspen",
        "Logitech",
        "Lowepro",
        "Manfrotto",
        "Minolta",
        "Motorola",
        "National Geographic",
        "Nextbase",
        "Nikon",
        "Nixplay",
        "Nokia",
        "Nomatic",
        "Olympus",
        "Panasonic",
        "Paw Patrol",
        "Peak Design",
        "Peppa Pig",
        "Pet Cube",
        "Photo Creator",
        "Platinum",
        "Polaroid",
        "Polaroid Go",
        "Powershot",
        "PowerVision",
        "Razer",
        "Rexing",
        "Ring",
        "RØDE",
        "Ryze Tech",
        "Samsung",
        "SanDisk",
        "Saramonic",
        "Savage",
        "Savage Universal",
        "Shure",
        "Sigma",
        "Snaptain",
        "Sony",
        "Sunpak",
        "Tamron",
        "Ted Bekker",
        "TomTom",
        "Tomy Games",
        "TP-Link",
        "Tu",
        "Vivitar",
        "VocoPro",
        "Vtech",
        "Yale",
        "Zhiyun",
        "Zoom",
        "Not Specified",
      ],
      Type: [
        "Compact",
        "Dash",
        "Handheld",
        "Helmet/Action",
        "Pocket",
        "Professional",
        "Spy Camera",
        "Not Specified",
      ],
      Megapixels: [
        "1",
        "2",
        "5",
        "6",
        "8",
        "9",
        "10",
        "12",
        "13",
        "14",
        "15",
        "16",
        "18",
        "20",
        "21",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "30",
        "32",
        "33",
        "42",
        "45",
        "47",
        "48",
        "50",
        "56",
        "61",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Music: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Brands: [
        "Studebaker",
        "SanDisk",
        "Victrola",
        "Edifier",
        "Insignia",
        "Bose",
        "GPX",
        "Jensen",
        "QFX",
        "Toshiba",
        "Bush",
        "Yamaha",
        "Chad Valley",
        "Bose",
        "RockJam",
        "Apple",
        "SanDisk",
        "Sony",
        "AGPTEK",
        "FiiO",
        "innioasis",
        "TIMMKOO",
        "Panasonic",
        "Samsung",
        "Philips",
        "SanDisk",
        "Creative",
        "iRiver",
        "Archos",
        "Cowon",
        "Aiwa",
        "Pioneer",
        "Microsoft",
        "RCA",
        "Fiio",
        "Astell&Kern",
        "HiFiMAN",
        "Xduoo",
        "AGPTEK",
        "Coby",
        "Benjie",
        "Ruizu",
        "Transcend",
        "Meizu",
        "Lotoo",
        "Not Specified",
      ],
      Connectivity: ["Aux", "Bluetooth", "USB", "Wi-Fi"],
      SupportedStandards: [
        "MP3",
        "AAC",
        "ACELP",
        "AIFF",
        "ALAC",
        "AMR",
        "APE",
        "ASF",
        "DSD",
        "DSF",
        "DXD",
        "FLAC",
        "M4A",
        "MP4",
        "OGG",
        "PCM",
        "WAV",
        "WMA",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Phone: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      Type: [
        "Cell Phones",
        "Cell Phone Accessories",
        "Landlines",
        "Walkie Talkies",
      ],
      CellPhones: {
        PriceRange: [
          "Up to $50",
          "$50 to $100",
          "$100 to $150",
          "$150 to $250",
          "$250 to $400",
          "$400 to $600",
          "$600 & above",
        ],
        Condition: [
          "Brand New",
          "Open Box",
          "Refurbished",
          "Used",
          "For Parts or Not Working",
          "Certified Pre-Owned",
        ],
        NetworkProvider: [
          "Unlocked",
          "AT&T Wireless",
          "Boost Mobile",
          "Cricket Wireless",
          "Simple Mobile",
          "Sprint",
          "Straight Talk",
          "T-Mobile",
          "Ting",
          "Total Wireless",
          "TracFone Wireless",
          "Verizon Wireless",
          "Virgin Mobile",
          "Uscellular",
          "Dish Wireless",
          "EE",
          "O2",
          "Three",
          "Vodafone",
          "1pMobile",
          "Asda Mobile",
          "BT Mobile",
          "CMLink",
          "Ecotalk",
          "Extreme Connect",
          "FreedomPop",
          "giffgaff",
          "iD Mobile",
          "IQ Mobile",
          "KC Mobile",
          "Lebara",
          "Lycamobile",
          "Now Mobile",
          "Plusnet Mobile",
          "RWG Mobile",
          "Sky Mobile",
          "SMARTY",
          "Spusu UK",
          "Superdrug Mobile",
          "Talkmobile",
          "Tesco Mobile",
          "Not Specified",
        ],
        Brand: [
          "Alcatel",
          "Apple",
          "ASHATA",
          "ASUS",
          "ASUS",
          "Bewinner",
          "Blackview",
          "BLU",
          "Bose",
          "CUBOT",
          "DOOGEE",
          "Dpofirs",
          "Easyfone",
          "ExAchat",
          "Google",
          "Hilitand",
          "HONOR",
          "Huawei",
          "Lamicall",
          "Lebara",
          "LG",
          "Lively",
          "Motorola",
          "Nokia",
          "nubia",
          "NUU",
          "OnePlus",
          "Oppo",
          "Realme",
          "RealPlus",
          "Samsung",
          "Sony",
          "TCL",
          "TracFone",
          "TTfone",
          "Ulefone",
          "UMIDIGI",
          "USHINING",
          "VANMASS",
          "Vivo",
          "Xgody",
          "Xiaomi",
          "Yoidesu",
          "Not Specified",
        ],
        OperatingSystem: [
          "Android",
          "Android Go",
          "iOS",
          "HarmonyOS",
          "KaiOS",
          "Tizen",
          "Ubuntu Touch",
          "Sailfish OS",
          "PureOS",
          "Plasma Mobile",
          "Nucleus OS",
          "Symbian",
          "Feature",
          "MIUI",
          "Series 30+",
          "S30+",
          "Not Specified",
        ],
        ScreenSizeRange: [
          '5"& under',
          '5" to 5.9"',
          '5" to 5.9"',
          '6" to 6.9"',
          '6" to 6.9"',
          '7" and over',
          "Foldable phones",
          "Not Specified",
        ],
        MemoryCapacity: [
          "512 MB",
          "1 GB",
          "2 GB",
          "3 GB",
          "4 GB",
          "6 GB",
          "8 GB",
          "12 GB",
          "16 GB",
          "18 GB",
          "32 GB",
          "64 GB",
          "128 GB",
          "256 GB",
          "512 GB & Above",
          "Not Specified",
        ],
        CameraResolution: [
          "Up to 2.9 MP",
          "3 to 4.9 MP",
          "5 to 7.9 MP",
          "8 to 12.9 MP",
          "13 to 19.9 MP",
          "20 MP & above",
          "Not Specified",
        ],
        BatteryCapacity: [
          "Under 1,000 mAh",
          "1,000 - 1,999 mAh",
          "2,000 - 2,999 mAh",
          "3,000 - 3,999 mAh",
          "4,000 - 4,999 mAh",
          "5,000 - 5,999 mAh",
          "6,000 - 6,999 mAh",
          "Not Specified",
        ],
        Colour: [
          "Black",
          "White",
          "Stainless Steel/Silver",
          "Grey/Charcoal",
          "Space Grey",
          "Metallic Finishes",
          "Red",
          "Blue",
          "Green",
          "Yellow",
          "Orange",
          "Purple",
          "Gold",
          "Rose Gold",
          "Sandstone",
          "Pink",
          "Cream/Ivory",
          "Wood Finishes",
          "Transparent or Clear",
          "Patterned or Themed Designs",
          "Brushed Finishes",
          "Not Specified",
        ],
        WarrantyInformation: [
          "Manufacturer's Warranty",
          "Extended Warranty",
          "Limited Warranty",
          "Full Warranty",
          "Express Warranty",
          "Implied Warranty",
          "No Warranty / As-Is",
        ],
        SellerRating: ["5*", "4*", "3*", "2*", "1*"],
      },
      CellPhoneAccessories: {
        AccessoryType: [
          "Phone chargers",
          "Mains Chargers",
          "Magsafe Chargers",
          "Wireless Chargers",
          "Power banks",
          "Phone cases",
          "Screen protectors",
          "In Car accessories",
          "SIM Cards",
          "Phone Storage",
          "USB Cables",
          "Lightning Cables",
          "Not Specified",
        ],
        PriceRange: [
          "Under $25",
          "$25 to $50",
          "$50 to $100",
          "$100 to $200",
          "$200 & Above",
        ],
        Condition: [
          "Brand New",
          "Open Box",
          "Refurbished",
          "Used",
          "For Parts or Not Working",
          "Certified Pre-Owned",
        ],
        WarrantyInformation: [
          "Manufacturer's Warranty",
          "Extended Warranty",
          "Limited Warranty",
          "Full Warranty",
          "Express Warranty",
          "Implied Warranty",
          "No Warranty / As-Is",
        ],
        SellerRating: ["5*", "4*", "3*", "2*", "1*"],
      },
      LandLine: {
        LandLineType: [
          "Cordless Phones",
          "Corded Phones",
          "Coded & Cordless Combos",
        ],
        PriceRange: [
          "Under $25",
          "$25 to $50",
          "$50 to $100",
          "$100 to $200",
          "$200 & Above",
        ],
        Condition: [
          "Brand New",
          "Open Box",
          "Refurbished",
          "Used",
          "For Parts or Not Working",
          "Certified Pre-Owned",
        ],
        Brand: [
          "BT",
          "Panasonic",
          "Vtech",
          "Binatone",
          "iDECT",
          "GPO",
          "Yealink",
          "Alcatel",
          "Gigaset",
          "Ligo",
          "Doro",
          "Cobra",
          "Swissvoice",
          "Geemarc",
          "Applicomms",
          "AT&T",
          "Motorola",
          "Tyler",
          "Sangyn",
          "iSoHo Phones",
          "TelPal",
          "Clarity",
          "Gekmor",
          "The VoIP Lounge",
          "FOSA",
          "Retevis",
          "ANSIOVON",
          "Arcshell",
          "BAOFENG",
          "BaoFeng",
          "BTECH",
          "Cobra",
          "COBRA",
          "DEWALT",
          "eSynic",
          "Greaval",
          "HYS",
          "HYSHIKRA",
          "Jeebuu",
          "JUCJET",
          "LUITON",
          "Midland",
          "MOICO",
          "Motorola Solutions",
          "PNI",
          "pxton",
          "Radioddity",
          "radtel",
          "Retevis",
          "Rivins",
          "Rugged Radios",
          "SAMCOM",
          "UAYESOK",
          "Uniden",
          "Not Specified",
        ],
        WarrantyInformation: [
          "Manufacturer's Warranty",
          "Extended Warranty",
          "Limited Warranty",
          "Full Warranty",
          "Express Warranty",
          "Implied Warranty",
          "No Warranty / As-Is",
        ],
        SellerRating: ["5*", "4*", "3*", "2*", "1*"],
      },
      WalkieTalkies: {
        LandLineType: [
          "Cordless Phones",
          "Corded Phones",
          "Coded & Cordless Combos",
        ],
        PriceRange: [
          "Under $25",
          "$25 to $50",
          "$50 to $100",
          "$100 to $200",
          "$200 & Above",
        ],
        Condition: [
          "Brand New",
          "Open Box",
          "Refurbished",
          "Used",
          "For Parts or Not Working",
          "Certified Pre-Owned",
        ],
        Brand: [
          "BT",
          "Panasonic",
          "Vtech",
          "Binatone",
          "iDECT",
          "GPO",
          "Yealink",
          "Alcatel",
          "Gigaset",
          "Ligo",
          "Doro",
          "Cobra",
          "Swissvoice",
          "Geemarc",
          "Applicomms",
          "AT&T",
          "Motorola",
          "Tyler",
          "Sangyn",
          "iSoHo Phones",
          "TelPal",
          "Clarity",
          "Gekmor",
          "The VoIP Lounge",
          "FOSA",
          "Retevis",
          "ANSIOVON",
          "Arcshell",
          "BAOFENG",
          "BaoFeng",
          "BTECH",
          "Cobra",
          "COBRA",
          "DEWALT",
          "eSynic",
          "Greaval",
          "HYS",
          "HYSHIKRA",
          "Jeebuu",
          "JUCJET",
          "LUITON",
          "Midland",
          "MOICO",
          "Motorola Solutions",
          "PNI",
          "pxton",
          "Radioddity",
          "radtel",
          "Retevis",
          "Rivins",
          "Rugged Radios",
          "SAMCOM",
          "UAYESOK",
          "Uniden",
          "Not Specified",
        ],
        WarrantyInformation: [
          "Manufacturer's Warranty",
          "Extended Warranty",
          "Limited Warranty",
          "Full Warranty",
          "Express Warranty",
          "Implied Warranty",
          "No Warranty / As-Is",
        ],
        SellerRating: ["5*", "4*", "3*", "2*", "1*"],
      },
    },
    GamingConsole: {
      SearchWithIn: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: [
        "Consoles",
        "Controllers",
        "PC gaming",
        "Video Games",
        "Video Game Accessories",
        "Virtual reality",
        "Not Listed",
      ],
      Brand: [
        "Razer",
        "ROCCAT",
        "Thrustmaster",
        "Anda Seat",
        "Astro",
        "Astro Gaming",
        "ASUS",
        "Backbone",
        "Blaze Entertainment",
        "Blue",
        "Blue Microphones",
        "Cable Guy",
        "Cable Guys",
        "CATAN",
        "Company of Heroes",
        "Corsair",
        "Corsair",
        "Daija",
        "Deltaco",
        "Elgato",
        "Evercade",
        "Excalibur Games",
        "Football Manager",
        "Geek Squad",
        "Gioteck",
        "HORI",
        "Hyper Mega Tech",
        "Hyperkin",
        "HyperX",
        "IMP",
        "IMP Gaming",
        "IMP Tech",
        "JBL",
        "Lenovo",
        "Lexibook",
        "Logitech",
        "Logitech Astro",
        "Logitech G",
        "Maxx Tech",
        "META",
        "Microsoft",
        "Minecraft",
        "MSI",
        "My Arcade",
        "Nacon",
        "Nintendo",
        "Ntense",
        "Numskull",
        "PDP",
        "Playseat",
        "PlayStation",
        "Pokeman",
        "Power Gaming",
        "PowerA",
        "Razer",
        "RDS Industries",
        "RED5",
        "Retro Gaming",
        "RIG",
        "RiotPWR",
        "Rubber Road",
        "Rust",
        "Samsung",
        "SanDisk",
        "SCUFF",
        "Seagate",
        "Skullcandy",
        "Sony",
        "STEALTH",
        "SteelSeries",
        "Thrustmaster",
        "Tramsim",
        "Trust",
        "Turtle Beach",
        "Twinkly",
        "Venom",
        "Victrix",
        "WD",
        "X Rocker",
        "Xbox",
        "Not Listed",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Wearable: {
      SearchWithIn: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: [
        "Smartwatches",
        "Fitness trackers",
        "Oura ring",
        "Alternative wearables",
        "Health & Personal Care",
        "Bands",
        "Chargers",
        "Screen protectors",
        "Not Listed",
      ],
      Brand: [
        "Amazfit",
        "Apple",
        "Ben Sherman",
        "Casio",
        "Citizen",
        "Disney",
        "Fitbit",
        "Fossil",
        "Garmin",
        "Google Pixel",
        "Harry Lime",
        "hecere",
        "Henry London",
        "Huawei",
        "LaNikar",
        "Meta Quest",
        "Nuband",
        "Radley",
        "Radley London",
        "Reflex Active",
        "Samsung",
        "Sekonda",
        "Spirit",
        "Ticwatch",
        "Tikkers",
        "Tovimall",
        "WHOOP",
        "Withings",
        "WITHit",
        "Zagg",
        "Not Listed",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Networking: {
      SearchWithIn: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: [
        "Wi-Fi & Networking",
        "Routers",
        "Wi-Fi Extenders",
        "Wireless Access Points",
        "USB Wi-Fi Adapters",
        "Not Listed",
      ],
      Brand: [
        "Alcatel",
        "Alfa",
        "AMX",
        "Apple",
        "ARRIS",
        "Aruba",
        "ASUS",
        "AVM",
        "BASEUS",
        "Belkin",
        "BT",
        "Cisco",
        "Devolo",
        "Disney",
        "D-Link",
        "DrayTek",
        "EDIMAX",
        "EE",
        "eero",
        "Esinkin",
        "F-Secure",
        "GL.iNet",
        "Glocalme",
        "Google",
        "Grandstream",
        "Gryphon",
        "HP",
        "HPE",
        "HPE Aruba",
        "Huawei",
        "Insignia",
        "iPort",
        "j5create",
        "Kinivo",
        "Kuwfi",
        "Lenovo",
        "Linksys",
        "Linksys",
        "Logitech",
        "Logitech G",
        "MacAfee",
        "magic-jack",
        "Mercury",
        "MikroTik",
        "MikroTik",
        "Motorola",
        "NETGEAR",
        "Norton",
        "NovAtel",
        "O2",
        "Option",
        "Pakedge",
        "Polycom",
        "QNAP",
        "Samsung",
        "Silex Technology",
        "Sky",
        "Solis",
        "SonicWALL",
        "StarTech",
        "TalkTalk",
        "TDK",
        "Telekom",
        "Telstra",
        "Tenda",
        "T-Mobile",
        "TP-LINK",
        "TP-Link",
        "Trend Micro",
        "TRENDnet",
        "Ubiquiti Networks",
        "Universal",
        "Verizon",
        "Vodafone",
        "VONETS",
        "WatchGuard",
        "Wavlink",
        "ZTE",
        "ZyXEL",
        "Not listed",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    ComputerComponents: {
      SearchWithIn: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Brand: [
        "WD",
        "CORSAIR",
        "MSI",
        "AMD",
        "Samsung",
        "XFX",
        "ASUS",
        "Cooler Master",
        "Intel",
        "Samsung",
        "SanDisk",
        "ASUS",
        "CORSAIR",
        "Seagate",
        "MSI",
        "PNY",
        "Western Digital",
        "Gigabyte",
        "PowerColor",
        "HP",
        "Protech & Store",
        "Toshiba",
        "Elements Portable",
        "Apple",
        "Logitech",
        "Thermaltake",
        "NZXT",
        "Crucial",
        "Solidigm",
        "Toshiba",
        "G Tech",
        "Lacie",
        "Not Listed",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    OfficeEquipment: {
      SearchWithIn: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: [
        "Computers",
        "Printers",
        "Scanners",
        "Photocopiers",
        "Telephones",
        "Shredders",
        "Projectors",
        "Monitors & Screens",
        "Networking Equipment",
        "Storage Devices",
        "Office Furniture",
        "Stationery",
        "Whiteboards & Blackboards",
        "Bulletin Boards & Display Panels",
        "Calculators",
        "Fax Machines",
        "Label Makers",
        "Time Clocks & Attendance Systems",
        "Paper Handling Equipment",
        "Audio/Video Equipment",
        "Security Devices",
        "Mailroom Equipment",
        "Office Supplies",
        "Software",
        "Presentation Tools",
        "Not Listed",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Security: {
      SearchWithIn: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: [
        "CCTV Cameras",
        "Digital Video Recorders",
        "Alarm Systems",
        "Access Control Systems",
        "Intercom Systems",
        "Perimeter Security Systems",
        "Surveillance Software",
        "Drone Surveillance",
        "Body-Worn Cameras",
        "Vehicle Tracking Systems",
        "Hidden/Covert Cameras",
        "Thermal Imaging Cameras",
        "Automated License Plate Recognition Systems",
        "Metal Detectors",
        "X-Ray Scanners",
        "Explosive Trace Detectors",
        "Chemical Agent Detectors",
        "Under Vehicle Surveillance Systems",
        "Security Mirrors",
        "Barriers and Bollards",
        "Guard Tour Systems",
        "Cybersecurity Tools",
        "Smart Home Security Devices",
        "Audio Surveillance Equipment",
        "Lighting for Security Purposes",
        "Not Listed",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Audio: {
      SearchWithIn: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: [
        "Microphones",
        "Headphones & Earphones",
        "Loudspeakers",
        "Mixers",
        "Audio Interfaces",
        "Amplifiers",
        "Digital Audio Workstations",
        "Signal Processors",
        "Cables & Connectors",
        "Recording Devices",
        "DJ Equipment",
        "PA Systems",
        "Rackmount Gear",
        "Portable Audio Players",
        "Karaoke Systems",
        "Acoustic Treatment",
        "Audio Analyzers",
        "Studio Monitors",
        "Instrument Amplifiers",
        "Wireless Systems",
        "Turntables & Record Players",
        "CD Players & Recorders",
        "Audio Racks & Cases",
        "Megaphones",
        "Stage & Lighting Equipment",
        "Broadcasting Equipment",
        "Boomboxes",
        "Radios",
        "Clock Radios",
        "TV Stands",
        "Record Player",
        "DVD Players",
        "Not Listed",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    HomeDevice: {
      SearchWithIn: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: [
        "Smart Speakers and Hubs",
        "Smart Lighting",
        "Smart Thermostats",
        "Smart Security Cameras",
        "Smart Locks and Doorbells",
        "Smart Plugs and Switches",
        "Smart Smoke & Carbon Monoxide Detectors",
        "Smart Home Appliances",
        "Smart Blinds and Curtains",
        "Smart Irrigation Systems",
        "Smart Health & Fitness Devices",
        "Smart TVs & Streaming Devices",
        "Smart Home Sensors",
        "Smart Vacuum Cleaners",
        "Smart Air Purifiers & Humidifiers",
        "Smart Pet Care Products",
        "Smart Energy Monitors",
        "Smart Garden Devices",
        "Not Listed",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Batteries: {
      SearchWithIn: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: [
        "Non-rechargeable Batteries",
        "Rechargeable Batteries",
        "Specialty Batteries",
        "Power Supplies",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
  },

  estate: {
    listing: ["Buy", "Rent", "Sell", "International", "Holiday Rentals"],
    property: [
      "House",
      "Condominium",
      "Apartment/Flat",
      "Commericial",
      "Farmhouse",
      "Land",
      "Industrial",
      "Room",
      "Other",
    ],
    bedrooms: ["0", "1", "2", "3", "4", "5+"],
    bathrooms: ["0", "1", "2", "3", "4", "5+"],
    tenure: ["Freehold", "Leasehold", "Unknown"],
    propertyCondition: ["Excellent", "Good", "In need of repair"],
    key: [
      "Detached property",
      "Garage",
      "Double garage",
      "Private garden",
      "Communal garden",
      "Open plan living",
      "Gated community",
      "Balcony",
    ],
    nearest: [
      "Primary school",
      "Secondary school",
      "University",
      "Hospital",
      "Public transport",
      "Airport",
      "Restaurants & cafes",
      "Shopping centre",
      "Public park",
      "Beach",
    ],
    facilities: [
      "Private parking",
      "Off road parking",
      "Internet",
      "Pets allowed",
      "Room service",
      "Shower",
      "Smoke alarms",
      "Fire extinguishers",
      "Washing machine",
      "Dishwasher",
      "Microwave",
      "Refrigerator",
      "Kitchenware",
      "Oven",
      "Dining area",
      "Seating Area",
      "Private entrance",
      "Heating",
      "Air conditioning",
      "Built-in wardrobes",
      "Fitten kitchen",
      "Disabled person facilities",
      "Private swimming pool",
      "Communal swimming pool",
      "Games Room",
      "Underfloor heating",
    ],
  },

  truck: {
    vehicleType: [
      "Aircraft",
      "Boats & Watercraft",
      "Cars",
      "Classic Cars",
      "Commericial Trucks",
      "Motorcycles",
      "RV & Motorhomes",
      "SUVs",
      "Trucks",
      "Utility & Work Trailers",
      "Vans",
      "Bikes",
      "Heavy Machinery",
      "Vehicles Wanted",
    ],
    saleType: ["Private Seller", "Trader"],
    condition: ["Brand new", "Used", "Accident damaged"],
    make: ["Make 1", "Make 2"],
    model: ["Model 1", "Model 2"],
    year: [
      ...[...new Array(new Date().getFullYear() - 1899)].map((_, index) => {
        return (
          index +
          new Date(Date.now()).getFullYear() -
          (new Date(Date.now()).getFullYear() - 1900)
        ).toString();
      }),
    ].reverse(),
    gearBox: ["Manual", "Automatic"],
    fualType: [
      "Gasoline",
      "Petrol",
      "Diesel",
      "Liquefied petroleum gas (LPG)",
      "Compressed Natural Gas (CNG)",
      "Micro Hybrid",
      "Mild Hybrid",
      "Mild Hybrid Electric Vehicle (MHEV)",
      "Hybrid Electric Vehicle (HEV)",
      "Plug-in Hybrid Electric Vehicle (PHEV)",
      "Battery Electric Vehicle (BEV)",
      "Hydrogen Fuel Cell Electric Vehicle (FCEV)",
      "Other",
    ],
    doors: ["1", "2", "3", "4", "5", "6", "7"],
    color: [
      "Beige",
      "Black",
      "Blue",
      "Bronze",
      "Brown",
      "Burgundy",
      "Gold",
      "Green",
      "Grey",
      "Indigo",
      "Magenta",
      "Maroon",
      "Multicolour",
      "Navy",
      "Orange",
      "Pink",
      "Purple",
      "Red",
      "Silver",
      "Turquoise",
      "White",
      "Yellow",
    ],
    bodyType: [
      "Hatchback",
      "Estate/Wagon",
      "SUV",
      "Saloon/Sedan",
      "Coupe",
      "Convertible",
      "Van/Minivan",
      "Truck/Pickup",
    ],
    seats: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19+",
    ],
  },
};
