export const selectData = {
  pet: {
    category: ["Pets for sale", "Pets for adoption", "Pet Supplies"],
    PetsSupplies: {
      Type: [
        "Food",
        "Treats  & Edible Chews",
        "Toys & Apparel",
        "Grooming & Pet Health",
        "Supplies",
        "Flea & Tick Control",
        "Shops",
      ],
      PetType: [
        "Dogs",
        "Cats",
        "Birds",
        "Fish",
        "Reptile",
        "Rabbits",
        "Rodents",
        "Livestock",
        "Horses",
        "Amphibian",
        "Other Pet",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
    },
    Petsforsale: {
      Type: [
        "Dogs",
        "Cats",
        "Birds",
        "Fish",
        "Reptile",
        "Rabbits",
        "Rodents",
        "Livestock",
        "Horses",
        "Amphibian",
      ],
      Dogs: {
        SearchWithin: [
          "Current location",
          "Within 1 mile",
          "Within 5 miles",
          "Within 15 miles",
          "Within 30 miles",
          "Within 50 miles",
          "Within 100 miles",
          "Within 200 miles",
          "Nationwide",
        ],
        Breed: [
          "Affenpinscher",
          "Afghan Hound",
          "Airedale Terrier",
          "Akita",
          "Alapaha Blue Blood Bulldog",
          "Alaskan Malamute",
          "American Bulldog",
          "American Bully",
          "American Cocker Spaniel",
          "American Hairless Terrier",
          "American Pocket Bullie",
          "Anatolian Shepherd",
          "Australian Cattle Dog",
          "Australian Kelpie",
          "Australian Shepherd",
          "Australian Silky Terrier",
          "Australian Terrier",
          "Basenji",
          "Basset Bleu De Gascogne",
          "Basset Fauve De Bretagne",
          "Basset Griffon Vendeen",
          "Basset Hound",
          "Bavarian Mountain Hound",
          "Beagle",
          "Bearded Collie",
          "Beauceron",
          "Bedlington Terrier",
          "Belgian Shepherd",
          "Bergamasco",
          "Bernese Mountain Dog",
          "Bichon Frise",
          "Biewer Terrier",
          "Bloodhound",
          "Boerboel",
          "Bolognese",
          "Border Collie",
          "Border Terrier",
          "Borderdoodle",
          "Borzoi",
          "Boston Terrier",
          "Bouvier Des Flandres",
          "Boxador",
          "Boxer",
          "Bracco Italiano",
          "Braque D'auvergne",
          "Briard",
          "Brittany Spaniel",
          "Bullmastiff",
          "Cairn Terrier",
          "Canaan Dog",
          "Canadian Eskimo Dog",
          "Cane Corso",
          "Catalan Sheepdog",
          "Caucasian Shepherd Dog",
          "Cavachon",
          "Cavalier King Charles Spaniel",
          "Cavapoo",
          "Central Asian Shepherd",
          "Cesky Terrier",
          "Chesapeake Bay Retriever",
          "Chihuahua",
          "Chinese Crested Dog",
          "Chipoo",
          "Chorkie",
          "Chow Chow",
          "Chug",
          "Clumber Spaniel",
          "Cock-a-chon",
          "Cockapoo",
          "Cocker Jack",
          "Cocker Spaniel",
          "Coonhound",
          "Coton De Tulear",
          "Curly Coated Retriever",
          "Dachshund",
          "Dalmatian",
          "Dandie Dinmont Terrier",
          "Deerhound",
          "Dobermann",
          "Dogue De Bordeaux",
          "Dorset Old Tyme Bulldogge",
          "English Bull Terrier",
          "English Bulldog",
          "English Setter",
          "English Springer Spaniel",
          "English Toy Terrier",
          "Entlebucher Mountain Dog",
          "Estrela Mountain Dog",
          "Eurasier",
          "Field Spaniel",
          "Finnish Lapphund",
          "Finnish Spitz",
          "Flat Coated Retriever",
          "Fox Terrier",
          "Foxhound",
          "French Bulldog",
          "German Longhaired Pointer",
          "German Shepherd",
          "German Shorthaired Pointer",
          "German Spitz",
          "German Wirehaired Pointer",
          "Giant Schnauzer",
          "Glen Of Imaal Terrier",
          "Goldador",
          "Golden Retriever",
          "Goldendoodle",
          "Gordon Setter",
          "Grand Bleu De Gascogne",
          "Great Dane",
          "Greater Swiss Mountain Dog",
          "Greenland Dog",
          "Greyhound",
          "Griffon Bruxellois",
          "Hamiltonstovare",
          "Harrier",
          "Havanese",
          "Hovawart",
          "Hungarian Puli",
          "Hungarian Pumi",
          "Hungarian Vizsla",
          "Huntaway",
          "Huskamute",
          "Huskita",
          "Ibizan Hound",
          "Irish Setter",
          "Irish Terrier",
          "Irish Water Spaniel",
          "Irish Wolfhound",
          "Italian Greyhound",
          "Italian Spinone",
          "Jack Russell",
          "Jack Tzu",
          "Jackachon",
          "Jackapoo",
          "Jackawawa",
          "Jagdterrier",
          "Japanese Akita",
          "Japanese Chin",
          "Japanese Spitze",
          "Jug",
          "Keeshond",
          "Kerry Blue Terrier",
          "King Charles Spaniel",
          "Komondor",
          "Kooikerhondje",
          "Korthals Griffon",
          "Kromfohrlander",
          "Labradinger",
          "Labradoodle",
          "Labrador Retriever",
          "Lagotto Romagnolo",
          "Lakeland Terrier",
          "Lancashire Heeler",
          "Large Munsterlander",
          "Leonberger",
          "Lhasa Apso",
          "Lhasapoo",
          "Lowchen",
          "Lurcher",
          "Malshi",
          "Maltese",
          "Maltipoo",
          "Manchester Terrier",
          "Maremma Sheepdog",
          "Mastiff",
          "Mexican Hairless",
          "Miniature Dachshund",
          "Miniature Pinscher",
          "Miniature Poodle",
          "Miniature Schnauzer",
          "Mixed Breed",
          "Morkie",
          "Neapolitan Mastiff",
          "Newfoundland",
          "Norfolk Terrier",
          "Northern Inuit",
          "Norwegian Elkhound",
          "Norwich Terrier",
          "Nova Scotia Duck Tolling Retriever",
          "Old English Sheepdog",
          "Otterhound",
          "Papillon",
          "Parson Russell Terrier",
          "Patterdale Terrier",
          "Patterjack",
          "Pekingese",
          "Pharaoh Hound",
          "Picardy Spaniel",
          "Pinscher",
          "Plummer Terrier",
          "Pointer",
          "Polish Lowland Sheepdog",
          "Pomchi",
          "Pomeranian",
          "Pomskie",
          "Poochon",
          "Poodle",
          "Portuguese Podengo",
          "Portuguese Sheepdog",
          "Portuguese Water Dog",
          "Presa Canario",
          "Pugalier",
          "Pugapoo",
          "Puggles",
          "Pug",
          "Pugzu",
          "Pyrenean Mastiff",
          "Pyrenean Mountain Dog",
          "Pyrenean Sheepdog",
          "Rhodesian Ridgeback",
          "Romanian Mioritic Shepherd",
          "Rottweiler",
          "Rough Collie",
          "Russian Black Terrier",
          "Russian Toy Terrier",
          "Saarloos Wolfdog",
          "Saint Bernard",
          "Salukis",
          "Samoyed",
          "Schipperke",
          "Schnauzer",
          "Schnoodle",
          "Scottish Terrier",
          "Sealyham Terrier",
          "Shar Pei",
          "Shepadoodle",
          "Shetland Sheepdog",
          "Shiba Inu",
          "Shih Tzu",
          "Shihchon",
          "Shihpoo",
          "Shorkie",
          "Siberian Huskie",
          "Skye Terrier",
          "Sloughi",
          "Smooth Collie",
          "Soft Coated Wheaten Terrier",
          "Spanador",
          "Spanish Mastiff",
          "Spanish Water Dog",
          "Sporting Lucas Terrier",
          "Springador",
          "Sprocker",
          "Sprollie",
          "Sproodle",
          "Staffordshire Bull Terrier",
          "Sussex Spaniel",
          "Swedish Lapphund",
          "Swedish Vallhund",
          "Tamaskan",
          "Tibetan Mastiff",
          "Tibetan Spaniel",
          "Tibetan Terrier",
          "Toy Poodle",
          "Turkish Kangal",
          "Utonagan",
          "Weimaraner",
          "Welsh Collie",
          "Welsh Corgi Cardigan",
          "Welsh Corgi Pembroke",
          "Welsh Sheepdog",
          "Welsh Springer Spaniel",
          "Welsh Terrier",
          "West Highland Terrier",
          "Westiepoo",
          "Wheaten Terrier",
          "Whippet",
          "White Swiss Shepherd",
          "Yorkie Russell",
          "Yorkshire Terrier",
          "Other Breed",
        ],
        Age: [
          "Newborn: 0-2 months",
          "Puppy: 2-6 months",
          "Young: 6-12 months",
          "Adolescent: 1-2 years",
          "Adult: 2-6 years",
          "Fully grown: 7 years",
          "Mature Adult: 7-10 years",
          "Senior: 10 years and older",
        ],
        Gender: ["Male", "Female", "Pair", "Unsexed or Unknown", "Mixed"],
        Vaccinations: [
          "Fully Vaccinated",
          "Up-to-Date",
          "Non-Core Vaccinations",
          "Rabies Vaccinated",
          "Titers Tested",
          "Medical Exemption",
          "No Vaccinations",
          "Needs Vaccinations",
        ],
        SellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
      },
    },
  },
};
