export const selectData = {
  condition: [
    "New",
    "Like New",
    "Excellent",
    "Good",
    "Fair",
    "Poor",
    "For Parts or Not Working",
  ],
  searchWithin: [
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
    "Nationwide",
  ],
  age: [
    "Brand New",
    "Less than 1 year old",
    "1 - 3 years old",
    "3 - 5 years old",
    "5 - 10 years old",
    "10 - 20 years old",
    "Over 20 years old",
    "Not Specified",
  ],
  brand: [
    "Fender",
    "Gibson",
    "Ibanez",
    "Martin",
    "Taylor",
    "Yamaha",
    "PRS (Paul Reed Smith)",
    "Epiphone",
    "ESP",
    "Jackson",
    "Rickenbacker",
    "Gretsch",
    "Steinway & Sons",
    "Yamaha",
    "Kawai",
    "Casio",
    "Fazioli",
    "Roland",
    "Bosendorfer",
    "Nord",
    "Kurzweil",
    "Moog",
    "Pearl",
    "Ludwig",
    "Tama",
    "DW (Drum Workshop)",
    "Zildjian",
    "Sabian",
    "Roland",
    "Yamaha",
    "Gretsch Drums",
    "Mapex",
    "Selmer",
    "Yamaha",
    "Bach",
    "Conn",
    "Buffet Crampon",
    "Jupiter",
    "Vandoren",
    "D'Addario",
    "Stradivarius",
    "Yamaha",
    "Stentor",
    "Cecilio",
    "Hohner",
    "Pearl River",
    "Suzuki",
    "ROLI",
    "Meinl",
    "Other brand",
  ],
  sellerType: [
    "Individual/Private Seller",
    "Music Store/Retailer",
    "Authorized Dealer",
    "Luthier/Builder",
    "Wholesaler/Distributor",
    "Educational Institution",
    "Rental Company",
    "Consignment Seller",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
