export const selectData = {
  forSale: {
    category: [
      "Televisions",
      "Laptops and Desktop Computers",
      "iPad, Tablets & eReaders",
      "Phones",
      "Gaming Consoles and Accessories",
      "Home Theater Systems",
      "Kitchen Appliances",
      "Laundry Appliances",
      "Cleaning Appliances",
      "Heating, Cooling, and Air Quality",
      "Personal Care Appliances",
      "Miscellaneous Appliances",
      "Cameras and Camcorders",
      "Portable Music Players",
      "Wearable Technology",
      "Networking Devices",
      "Computer Components and Storage",
      "Office Equipment",
      "Security and Surveillance Equipment",
      "Audio Equipment",
      "Smart Home Devices",
      "Batteries and Power Supplies",
    ],
    Televisions: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $50",
        "$50 - $100",
        "$100 - $300",
        "$300 - $600",
        "$600 - $1,000",
        "Over $1,000",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      ScreenSize: [
        "12 inches",
        "15 inches",
        "19 inches",
        "20 inches",
        "22 inches",
        "24 inches",
        "28 inches",
        "32 inches",
        "36 inches",
        "40 inches",
        "42 inches",
        "43 inches",
        "48 inches",
        "49 inches",
        "50 inches",
        "55 inches",
        "58 inches",
        "60 inches",
        "65 inches",
        "70 inches",
        "75 inches",
        "80 inches",
        "82 inches",
        "85 inches",
        "88 inches",
        "90 inches",
        "93 inches",
        "98 inches",
        "100+",
      ],
      Resolution: [
        "Standard Definition (SD)",
        "High Definition (HD)",
        "Full HD (FHD)",
        "Ultra HD (UHD)/4K",
        "8K",
        "8K Ultra High Dynamic",
      ],
      Brand: [
        "Samsung",
        "LG",
        "Sony",
        "Panasonic",
        "Vizio",
        "TCL",
        "Hisense",
        "Philips",
        "Sharp",
        "Toshiba",
        "Skyworth",
        "Xiaomi",
        "BPL",
        "Westinghouse",
        "Element",
        "Sceptre",
        "Haier",
        "Onida",
        "AOC",
        "Noble Skiodo",
        "Thomson",
        "JVC",
        "RCA",
        "Sanus",
        "SYLVOX",
        "ONN",
        "ATYME",
        "Soulaca",
        "continuus",
        "Google",
        "Cello",
        "Amazon",
        "ZOSHING",
        "Ferguson",
        "SYLVOX",
        "August",
        "Digihome",
        "AKAI",
        "Sorandy",
        "Finlux",
        "ciciglow",
        "ASHATA",
        "Avtex",
        "eSTAR",
        "Denver",
        "aspure",
        "AFGZQ",
        "MSEURO",
        "Not Specified",
      ],
      SmartTV: ["Yes", "No"],
      Colour: [
        "Black",
        "Black and White",
        "White",
        "Wooden Housings",
        "Beige and Off-White",
        "Silver and Grey",
        "Silver",
        "Metallic Finishes",
        "Transparent",
        "Blue",
        "Green",
        "Purple",
        "Orange",
        "Pink",
        "Brown",
        "Gold",
        "Multicoloured",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
    Laptops: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $50",
        "$50 - $100",
        "$100 - $300",
        "$300 - $600",
        "$600 - $1,000",
        "Over $1,000",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: ["Laptops", "Desktop PCs", "2 - in - 1"],
      Brand: [
        "Apple",
        "Dell",
        "HP (Hewlett-Packard)",
        "Lenovo",
        "ASUS",
        "Acer",
        "Microsoft",
        "Samsung",
        "Toshiba",
        "Razer",
        "Huawei",
        "Gigabyte and Aorus",
        "Fujitsu",
        "LG",
        "System76",
        "Not Specified",
      ],
      ramSize: [
        "4 KB",
        "64 KB",
        "128 KB",
        "1 MB",
        "2 MB",
        "16 MB",
        "32 MB",
        "512 MB",
        "1 GB",
        "2 GB",
        "3 GB",
        "4 GB",
        "6 GB",
        "8 GB",
        "16 GB",
        "32 GB",
        "64 GB",
        "128 GB",
        "256 GB",
        "Not Specified",
      ],
      processor: [
        "8086/8088",
        "286",
        "386",
        "486",
        "i5",
        "Alder Lake",
        "AMD 10h",
        "AMD FX",
        "AMD K5",
        "AMD K6",
        "AMD K8",
        "AMD Ryzen",
        "AMD Ryzen Mobile",
        "AMD Sempron",
        "AMD Turion",
        "APL0098",
        "APL0278",
        "APL2298",
        "Apple A10 Fusion",
        "Apple A10X Fusion",
        "Apple A11 Bionic",
        "Apple A12",
        "Apple A12 Bionic",
        "Apple A12X Bionic",
        "Apple A12Z Bionic",
        "Apple A13 Bionic",
        "Apple A14 Bionic",
        "Apple A15 Bionic",
        "Apple A16 Bionic",
        "Apple A17 Pro",
        "Apple A4",
        "Apple A5",
        "Apple A5X",
        "Apple A6",
        "Apple A6X",
        "Apple A7",
        "Apple A8",
        "Apple A8X",
        "Apple A9",
        "Apple A9X",
        "Apple M1",
        "Apple M1 Max",
        "Apple M1 Pro",
        "Apple M1 Ultra",
        "Apple M2",
        "Apple M2 Max",
        "Apple M2 Pro",
        "Apple M2 Ultra",
        "Apple M7",
        "Apple M8",
        "ARM",
        "Athlon",
        "Athlon 64",
        "Athlon 64 X2",
        "Bobcat",
        "Clarkdale",
        "Coffee Lake",
        "Core 2 Duo",
        "Core i3",
        "i386",
        "i486",
        "i9",
        "Intel 4004",
        "Intel 8008",
        "Intel 80286",
        "Intel 8080",
        "Intel 8085",
        "Intel 8086",
        "Intel 8088",
        "Intel Atom",
        "Intel Celeron",
        "Intel Core",
        "Intel Core 2",
        "Intel Core 2 Quad",
        "Intel Core i3",
        "Intel Core i7",
        "Intel Core i9",
        "Intel Pentium",
        "Intel Xeon",
        "Itanium",
        "M series",
        "Micro-controller",
        "Motorola 68000",
        "NEC V30",
        "Opteron",
        "Pentium",
        "Pentium 4",
        "Pentium D",
        "Pentium II",
        "Pentium III",
        "Pentium M",
        "Pentium Pro",
        "PowerPC",
        "Sandy Bridge",
        "Sempron",
        "Skylake",
        "SPARC",
        "Steamroller",
        "Tiger Lake",
        "x86-64",
        "Yonah",
        "Zen",
        "Not Specified",
      ],
      ScreenSize: [
        "11.6 inches",
        "12 inches",
        "12.5 inches",
        "13.3 inches",
        "14 inches",
        "15.6 inches",
        "17 inches",
        "17.3 inches",
        "18.4 inches",
        "19 inches",
        "20 inches",
        "21 inches",
        "22 inches",
        "24 inches",
        "27 inches",
        "32 inches",
        "Ultrawide Monitors",
        "Not Specified",
      ],
      StorageCapacity: [
        "10 MB",
        "20 MB",
        "80 MB",
        "160 MB",
        "250 MB",
        "320 MB",
        "16 GB",
        "32 GB",
        "64 GB",
        "120 GB",
        "128 GB",
        "256 GB",
        "500 GB",
        "512 GB",
        "1 TB",
        "2 TB",
        "3 TB",
        "4 TB",
        "5 TB",
        "6 TB",
        "7 TB",
        "8 TB",
        "9 TB",
        "10 TB",
        "11 TB",
        "12 TB",
        "13 TB",
        "14 TB",
        "15 TB",
        "16 TB",
        "20 TB",
        "Not Specified",
      ],
      OperatingSystem: [
        "Windows 11 Home",
        "Windows 11 Pro",
        "Windows 10 Home",
        "Windows 10 Home",
        "Windows 10 Pro",
        "Windows 10 Pro",
        "Windows 10 in S mode",
        "Windows Legacy System",
        "Mac OS",
        "Chrome OS",
        "Linux",
        "MS-DOS",
        "CP/M",
        "Unix",
        "iOS",
        "Android",
        "BSD",
        "Solaris",
        "AmigaOS",
        "OS/2",
        "BeOS",
        "Atari TOS",
      ],
      Colour: [
        "Black",
        "White",
        "Stainless Steel/Silver",
        "Grey/Charcoal",
        "Space Grey",
        "Metallic Finishes",
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Orange",
        "Purple",
        "Gold",
        "Rose Gold",
        "Sandstone",
        "Pink",
        "Cream/Ivory",
        "Wood Finishes",
        "Transparent or Clear",
        "Patterned or Themed Designs",
        "Brushed Finishes",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
      BatteryLife: [
        "Up to 4 hours",
        "5 to 7 hours",
        "8 to 10 hours",
        "11 hours & above",
      ],
    },
    Ipad: {
      SearchWithin: [
        "Within 1 mile",
        "Within 5 miles",
        "Within 15 miles",
        "Within 30 miles",
        "Within 50 miles",
        "Within 100 miles",
        "Within 200 miles",
        "Nationwide",
      ],
      PriceRange: [
        "Under $25",
        "$25 to $50",
        "$50 to $100",
        "$100 to $200",
        "$200 & Above",
      ],
      Condition: [
        "Brand New",
        "Open Box",
        "Refurbished",
        "Used",
        "For Parts or Not Working",
        "Certified Pre-Owned",
      ],
      Type: ["iPads", "Tablets", "eReaders"],
      Brand: [
        "Apple",
        "Samsung",
        "Microsoft",
        "Lenovo",
        "Huawei",
        "Amazon",
        "Asus",
        "LG",
        "Google",
        "Acer",
        "Dell",
        "Sony",
        "HP",
        "Xiaomi",
        "TCL",
        "Realme",
        "Amazon Kindle",
        "Kobo",
        "Barnes & Noble Nook",
        "PocketBook",
        "Bookeen",
        "Onyx Boox",
        "Remarkable",
        "Honor",
        "Alcatel",
        "Doro",
        "Entity",
        "Nokia",
        "TCL",
        "Blackview",
        "ApoloSign",
        "BYYBUO",
        "acer",
        "YOBANSE",
        "Aheadthink",
        "UMIDIGI",
        "DOOGEE",
        "YESTEL",
        "ZZB",
        "CUPEISI",
        "NORTH BISON",
        "WXUNJA",
        "PRITOM",
        "COOPERS",
        "AOCWEI",
        "MEIZE",
        "Aiprotablet",
        "COLORROOM",
        "NOBKLEN",
        "BAKEN",
        "OUKITEL",
        "A DREAMER",
        "Ematic",
        "ZONKO",
        "ANTEMPER",
        "Contixo",
        "BYANDBY",
        "TOPELOTEK",
        "JUNINKE",
        "AWOW",
        "CWOWDEFU",
        "Mouikei",
        "MoKo",
        "MESWAO",
        "AZMXDVP",
        "Fintie",
        "BOOX",
        "NORTH BISON",
        "SUPERDUODUO",
        "PocketBook",
        "BOOX",
        "Meebook",
        "ASHATA",
        "ENJOY-UNIQUE",
        "Kadimendium",
        "TECHGEAR",
        "Berfea",
        "kwmobile",
        "Zcooooool",
        "Not Specified",
      ],
      ScreenSize: [
        "7 Inches",
        "7.9 Inches",
        "8 Inches",
        "8.9 Inches",
        "9 Inches",
        "9.9 Inches",
        "10 Inches",
        "10.2 Inches",
        "10.5 Inches",
        "10.9 Inches",
        "11 Inches",
        "11.9 Inches",
        "12 Inches",
        "12.9 Inches",
        "13 Inches",
        "13.9 Inches",
        "14 Inches & above",
        "Not Specified",
      ],
      Storage: [
        "10 MB",
        "20 MB",
        "80 MB",
        "160 MB",
        "250 MB",
        "320 MB",
        "16 GB",
        "32 GB",
        "64 GB",
        "120 GB",
        "128 GB",
        "256 GB",
        "500 GB",
        "512 GB",
        "1 TB",
        "2 TB",
        "3 TB",
        "4 TB",
        "5 TB",
        "6 TB",
        "7 TB",
        "8 TB",
        "9 TB",
        "10 TB",
        "11 TB",
        "12 TB",
        "13 TB",
        "14 TB",
        "15 TB",
        "16 TB",
        "20 TB",
        "Not Specified",
      ],
      Memory: [
        "4 KB",
        "64 KB",
        "128 KB",
        "1 MB",
        "2 MB",
        "16 MB",
        "32 MB",
        "256 MB",
        "512 MB",
        "1 GB",
        "2 GB",
        "3 GB",
        "4 GB",
        "5 GB",
        "6 GB",
        "8 GB",
        "16 GB",
        "32 GB",
        "64 GB",
        "128 GB",
        "256 GB",
        "Not Specified",
      ],
      BatteryLife: [
        "Up to 3 hours",
        "4 to 6 hours",
        "7 to 9 hours",
        "10 to 13 hours",
        "14 hours & above",
      ],
      Colour: [
        "Black",
        "White",
        "Stainless Steel/Silver",
        "Grey/Charcoal",
        "Space Grey",
        "Metallic Finishes",
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Orange",
        "Purple",
        "Gold",
        "Rose Gold",
        "Sandstone",
        "Pink",
        "Cream/Ivory",
        "Wood Finishes",
        "Transparent or Clear",
        "Patterned or Themed Designs",
        "Brushed Finishes",
        "Not Specified",
      ],
      WarrantyInformation: [
        "Manufacturer's Warranty",
        "Extended Warranty",
        "Limited Warranty",
        "Full Warranty",
        "Express Warranty",
        "Implied Warranty",
        "No Warranty / As-Is",
      ],
      SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    },
  },

  estate: {
    listing: ["Buying", "Renting", "Selling"],
    property: [
      "House",
      "Condominium",
      "Apartment/Flat",
      "Commericial",
      "Farmhouse",
      "Land",
      "Industrial",
      "Room",
      "Other",
    ],
    bedrooms: ["1", "2", "3", "4", "5+", "None"],
    bathrooms: ["1", "2", "3", "4", "5+", "None"],
    tenure: ["Freehold", "Leasehold", "Unknown"],
    propertyCondition: ["Excellent", "Good", "In need of repair"],
    key: [
      "Detached property",
      "Garage",
      "Double garage",
      "Private garden",
      "Communal garden",
      "Open plan living",
      "Gated community",
      "Balcony",
    ],
    nearest: [
      "Primary school",
      "Secondary school",
      "University",
      "Hospital",
      "Public transport",
      "Airport",
      "Restaurants & cafes",
      "Shopping centre",
      "Public park",
      "Beach",
      "None",
    ],
    facilities: [
      "Private parking",
      "Off road parking",
      "Internet",
      "Pets allowed",
      "Room service",
      "Shower",
      "Smoke alarms",
      "Fire extinguishers",
      "Washing machine",
      "Dishwasher",
      "Microwave",
      "Refrigerator",
      "Kitchenware",
      "Oven",
      "Dining area",
      "Seating Area",
      "Private entrance",
      "Heating",
      "Air conditioning",
      "Built-in wardrobes",
      "Fitten kitchen",
      "Disabled person facilities",
      "Private swimming pool",
      "Communal swimming pool",
      "Games Room",
      "Underfloor heating",
    ],
  },

  truck: {
    vehicleType: [
      "Aircraft",
      "Boats & Watercraft",
      "Cars",
      "Classic Cars",
      "Commericial Trucks",
      "Motorcycles",
      "RV & Motorhomes",
      "SUVs",
      "Trucks",
      "Utility & Work Trailers",
      "Vans",
      "Bikes",
      "Heavy Machinery",
      "Vehicles Wanted",
    ],
    saleType: ["Private Seller", "Trader"],
    condition: ["Brand new", "Used", "Accident damaged"],
    make: ["Make 1", "Make 2"],
    model: ["Model 1", "Model 2"],
    year: [
      ...[...new Array(new Date().getFullYear() - 1899)].map((_, index) => {
        return (
          index +
          new Date(Date.now()).getFullYear() -
          (new Date(Date.now()).getFullYear() - 1900)
        ).toString();
      }),
    ].reverse(),
    gearBox: ["Manual", "Automatic"],
    fualType: [
      "Gasoline",
      "Petrol",
      "Diesel",
      "Liquefied petroleum gas (LPG)",
      "Compressed Natural Gas (CNG)",
      "Micro Hybrid",
      "Mild Hybrid",
      "Mild Hybrid Electric Vehicle (MHEV)",
      "Hybrid Electric Vehicle (HEV)",
      "Plug-in Hybrid Electric Vehicle (PHEV)",
      "Battery Electric Vehicle (BEV)",
      "Hydrogen Fuel Cell Electric Vehicle (FCEV)",
      "Other",
    ],
    doors: ["1", "2", "3", "4", "5", "6", "7"],
    color: [
      "Beige",
      "Black",
      "Blue",
      "Bronze",
      "Brown",
      "Burgundy",
      "Gold",
      "Green",
      "Grey",
      "Indigo",
      "Magenta",
      "Maroon",
      "Multicolour",
      "Navy",
      "Orange",
      "Pink",
      "Purple",
      "Red",
      "Silver",
      "Turquoise",
      "White",
      "Yellow",
    ],
    bodyType: [
      "Hatchback",
      "Estate/Wagon",
      "SUV",
      "Saloon/Sedan",
      "Coupe",
      "Convertible",
      "Van/Minivan",
      "Truck/Pickup",
    ],
    seats: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19+",
    ],
  },
};
