export const selectData = {
  condition: [
    "New",
    "Like New",
    "Gently Used",
    "Used",
    "Fair Condition",
    "For Parts or Not Working",
    "Refurbished",
    "Vintage/Antique",
  ],
  itemAge: [
    "Not Specified",
    "Brand New",
    "Less than 1 Year Old",
    "1-2 Years Old",
    "3-5 Years Old",
    "5-10 Years Old",
    "10+ Years Old",
    "Vintage",
    "Antique",
    "Not Applicable",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  sellerType: [
    "Not Specified",
    "Individual/Private Seller",
    "Professional Crafter/Artisan",
    "Small Business/Local Shop",
    "Commercial Retailer",
    "Online Retailers/E-commerce Store",
    "Wholesalers/Bulk Seller",
    "Artists/Designer",
    "Estate Sale/Antique Seller",
    "Workshop/Class",
    "Non-Profit Organization/Charity",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
