export const selectData = {
  condition: [
    "New",
    "Like New",
    "Gently Used",
    "Used",
    "Fair Condition",
    "For Parts or Not Working",
    "Refurbished",
    "Vintage/Antique",
  ],
  itemAge: [
    "0-6 Months",
    "6-12 Months",
    "1-2 Years",
    "3-4 Years",
    "5-7 Years",
    "8-10 Years",
    "11-13 Years",
    "14+ Years",
    "All Ages",
  ],
  itemBrand: [
    "Not Specified",
    "American Girl",
    "Bandai",
    "Barbie",
    "Bop It!",
    "Catan",
    "Cranium",
    "Crayola",
    "Disney",
    "Fisher-Price",
    "Funko",
    "Goliath Games",
    "HABA",
    "Hasbro",
    "Hot Wheels",
    "Jenga",
    "LeapFrog",
    "LEGO",
    "Little Tikes",
    "Marvel",
    "Mattel",
    "Mega Bloks",
    "Melissa & Doug",
    "Milton Bradley",
    "Monopoly",
    "Moose Toys",
    "My Little Pony",
    "Nerf",
    "Nintendo",
    "Parker Brothers ",
    "Play-Doh",
    "Playmobil",
    "Puzz 3D",
    "Ravensburger",
    "Ravensburger",
    "Schleich",
    "Spin Master",
    "Star Wars",
    "Tomy",
    "Transformers",
    "UNO",
    "VTech",
    "WowWee",
    "Zuru",
    "Other Brand",
  ],
  itemGender: [
    "Not Specified",
    "Boys",
    "Girls",
    "Unisex/Gender-Neutral",
    "No Preference",
  ],
  itemEducation: [
    "Not Specified",
    "STEM (Science, Technology, Engineering, Math)",
    "Literacy & Language",
    "Art & Creativity",
    "Cognitive Development",
    "Motor Skills",
    "Social & Emotional Learning",
    "Music & Rhythm",
    "Environmental Education",
    "History & Geography",
    "Logic & Strategy",
    "Multilingual Learning",
    "Sensory Play",
    "Life Skills",
    "Health & Nutrition",
    "Science Kits & Experiments",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  sellerType: [
    "Not Specified",
    "Individual/Private Seller",
    "Professional/Commercial Seller",
    "Authorized Dealer/Retailer",
    "Craftsman/Artisan",
    "Certified Pre-Owned",
    "Non-Profit/Organization",
    "Wholesaler/Bulk Seller",
    "Dropshipper",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
