export const selectData = {
  condition: [
    "New",
    "Like New",
    "Refurbished",
    "Used - Good",
    "Used - Fair",
    "For Parts or Not Working",
    "Vintage/Antique",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
    "Nationwide",
  ],
  sellerType: [
    "Not Specified",
    "Private Seller",
    "Dealer",
    "Business/Retailer",
    "Manufacturer",
    "Distributor/Wholesaler",
    "Non-Profit Organization/Charity",
    "Estate Sales",
    "Government Surplus",
  ],
  brand: [
    "Not Specified",
    "John Deere",
    "Husqvarna",
    "Stihl",
    "Toro",
    "Black & Decker",
    "Craftsman",
    "DeWalt",
    "Honda ",
    "Makita",
    "Echo",
    "Greenworks",
    "Weber",
    "Char-Broil",
    "Fiskars",
    "Suncast",
    "Karcher",
    "RYOBI",
    "Bosch",
    "Gardena",
    "Scotts",
    "Cub Cadet",
    "Poulan Pro",
    "Troy-Bilt",
    "Briggs & Stratton",
    "Hayward",
    "Intex",
    "Lifetime Products",
    "Keter",
    "Miracle-Gro",
    "Roundup",
    "Traeger",
    "Big Green Egg",
    "Other Manufacturer",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
