export const selectData = {
  condition: [
    "Mint",
    "Near Mint",
    "Excellent",
    "Very Good",
    "Good",
    "Fair",
    "Poor",
    "Restored",
    "As-Is",
    "For Parts or Not Working",
    "Reproduction/Replica",
    "Unsigned/Undated",
    "Customized/Altered",
  ],
  authenticity: [
    "Not Specified",
    "Original/Authentic",
    "Certified Authentic",
    "Signed by Artist/Manufacturer",
    "Unsigned",
    "Reproduction/Replica",
    "Licensed Copy",
    "Unknown/Authenticity Not Verified",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  age: [
    "Not Specified",
    "Prehistoric (before 3000 BCE)",
    "Ancient Egyptian (circa 3100 BCE – 30 BCE)",
    "Ancient Greek and Roman (circa 800 BCE – 476 CE)",
    "Early Medieval (circa 500 – 1000)",
    "High Medieval (circa 1000 – 1300)",
    "Late Medieval (circa 1300 – 1500)",
    "Renaissance (circa 1400 – 1600)",
    "Baroque (circa 1600 – 1750)",
    "Rococo (circa 1730 – 1760)",
    "Neoclassicism (circa 1760 – 1830)",
    "Romanticism (circa 1800 – 1850)",
    "Victorian Era (circa 1837 – 1901)",
    "Edwardian Era (circa 1901 – 1910)",
    "Art Nouveau (circa 1890 – 1910)",
    "Arts and Crafts Movement (circa 1880 – 1920)",
    "Art Deco (circa 1910 – 1940)",
    "Mid-Century Modern (circa 1933 – 1965)",
    "Post-War (1945 – 1960)",
    "Contemporary (1960s – 1990s)",
    "2000s",
    "2010s",
    "2020s",
    "Chinese Dynasties (e.g., Ming, Qing)",
    "Japanese Periods (e.g., Edo, Meiji)",
    "Indian Periods (e.g., Mughal, British Raj)",
    "Middle Eastern (e.g., Ottoman, Persian)",
    "African (pre-colonial, colonial, post-colonial periods)",
    "Pre-Columbian (Americas before 1492)",
    "Indigenous Art (various regions and times)",
    "Folk Art Era",
    "Military/War Time Eras (e.g., World War I, World War II)",
    "Space Age (mid-20th century onwards)",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
  type: {
    Art: [
      "Not Listed",
      "Paintings",
      "Sculptures",
      "Prints",
      "Photography",
      "Drawings",
      "Mixed Media",
      "Folk Art & Indigenous Art",
      "Textile Art",
    ],
    Collectibles: [
      "Not Listed",
      "Coins & Currency",
      "Stamps",
      "Comic Books & Graphic Novels",
      "Trading Cards",
      "Vintage Toys & Games",
      "Books & Manuscripts",
      "Records & Music Memorabilia",
      "Movie & TV Memorabilia",
      "Sports Memorabilia",
      "Antique Furniture",
      "Vintage Clothing & Accessories",
      "Watches & Clocks",
      "Jewellery",
      "Glass & Crystal",
      "Ceramics & Pottery",
      "Silver & Metalware",
      "Militaria",
      "Historical Memorabilia",
      "Ethnographic & Indigenous Artifacts",
      "Scientific & Medical Antiques",
      "Automobilia & Petroliana",
      "Numismatic Items",
      "Philatelic Items",
      "Antique Toys & Dolls",
      "Decorative Arts",
      "Vintage Posters & Signs",
      "Maps & Atlases",
      "Rugs & Carpets",
      "Photographic Equipment",
      "Railroadiana & Trains",
      "Nautical Antiques",
      "Architectural & Garden Antiques",
      "Religious Artifacts & Icons",
      "Political Memorabilia",
      "Tobacciana",
      "Breweriana & Beer Collectibles",
    ],
  },
};
