export const selectData = {
  type: {
    Seating: [
      "Not Listed",
      "Sofas & Couches",
      "Loveseats",
      "Armchairs",
      "Recliners",
      "Bean Bags",
      "Ottomans",
      "Stools",
      "Benches",
      "Dining Chairs",
      "Bar Stools",
    ],
    Tables: [
      "Not Listed",
      "Coffee Tables",
      "End Tables",
      "Dining Tables",
      "Bedside Tables",
      "Console Tables",
      "Bar Tables",
      "Desks",
      "Workstations",
    ],
    "Storage Furniture": [
      "Not Listed",
      "Bookcases",
      "Shelving Units",
      "Cabinets",
      "Sideboards",
      "Wardrobes",
      "Dressers",
      "Chests of Drawers",
      "TV Stands",
      "Storage Benches",
    ],
    "Beds & Bedroom Furniture": [
      "Not Listed",
      "Beds",
      "Bed Frames",
      "Headboards",
      "Nightstands",
      "Mattresses",
      "Bunk Beds",
      "Daybeds",
      "Futons",
    ],
    "Office Furniture": [
      "Not Listed",
      "Office Chairs",
      "Office Desks",
      "Filing Cabinets",
      "Bookshelves",
      "Conference Tables",
      "Computer Desks",
    ],
    "Outdoor Furniture": [
      "Not Listed",
      "Patio Chairs",
      "Outdoor Tables",
      "Garden Benches",
      "Hammocks",
      "Sun Loungers",
      "Outdoor Sofas",
    ],
    "Children’s Furniture": [
      "Not Listed",
      "Cribs",
      "Toddler Beds",
      "Kids' Chairs",
      "Kids' Desks",
      "Toy Storage",
    ],
    "Specialty Furniture": [
      "Not Listed",
      "Accent Pieces",
      "Hall Trees",
      "Coat Racks",
      "Room Dividers",
      "Vanity Tables",
      "Bar Carts",
      "Wine Racks",
    ],
    "Wall Decor": [
      "Not Listed",
      "Paintings",
      "Wall Mirrors",
      "Wall Clocks",
      "Wall Shelves",
      "Tapestries",
      "Wall Decals",
    ],
    Lighting: [
      "Not Listed",
      "Floor Lamps",
      "Table Lamps",
      "Chandeliers",
      "Wall Sconces",
      "Pendant Lights",
      "Ceiling Lights",
    ],
    Textiles: [
      "Not Listed",
      "Rugs",
      "Curtains",
      "Throw Pillows",
      "Blankets & Throws",
      "Bed Linens",
      "Towels",
    ],
    "Decorative Accents": [
      "Not Listed",
      "Vases",
      "Picture Frames",
      "Candles & Holders",
      "Sculptures",
      "Figurines",
      "Bookends",
    ],
    "Plants & Planters": [
      "Not Listed",
      "Indoor Plants",
      "Plant Pots",
      "Hanging Planters",
      "Terrariums",
    ],
    "Home Fragrance": [
      "Not Listed",
      "Diffusers",
      "Incense Holders",
      "Potpourri",
    ],
    "Seasonal Decor": [
      "Not Listed",
      "Christmas Decorations",
      "Halloween Decorations",
      "Other Holiday-Themed Items",
    ],
    Mirrors: [
      "Not Listed",
      "Full-Length Mirrors",
      "Bathroom Mirrors",
      "Decorative Mirrors",
    ],
    Clocks: [
      "Not Listed",
      "Mantel Clocks",
      "Grandfather Clocks",
      "Alarm Clocks",
    ],
    "Home Office Supplies": [
      "Not Listed",
      "Desk Organizers",
      "Stationery",
      "Bookends",
    ],
  },
  condition: ["New", "Used", "Refurbished", "Antique"],
  sellerType: ["Private Seller", "Store/Dealer"],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
