export const selectData = {
  type: {
    "Cardio Equipment": [
      "Treadmills",
      "Elliptical Trainers",
      "Stationary Bikes",
      "Rowing Machines",
      "Stair Climbers and Steppers",
      "Jump Ropes",
      "Treadclimbers",
    ],
    "Strength Training Equipment": [
      "Dumbbells",
      "Barbells and Weight Plates",
      "Kettlebells",
      "Weight Benches",
      "Home Gyms",
      "Resistance Bands",
      "Pull-Up Bars",
      "Medicine Balls",
      "Sandbags",
      "Power Racks and Squat Racks",
      "Smith Machines",
      "Cable Crossover Machines",
      "Leg Press Machines",
    ],
    "Yoga and Pilates": [
      "Yoga Mats",
      "Pilates Machines",
      "Exercise Balls",
      "Yoga Blocks",
      "Resistance Bands",
      "Pilates Rings",
      "Yoga Straps",
    ],
    "Boxing and Martial Arts": [
      "Punching Bags",
      "Boxing Gloves",
      "Sparring Gear",
      "Martial Arts Uniforms",
      "Training Pads",
      "Grappling Dummies",
    ],
    "Team Sports Equipment": [
      "Soccer Balls, Goals, and Nets",
      "Basketball Hoops and Balls",
      "Baseball Bats, Gloves, and Balls",
      "Footballs and Goal Posts",
      "Volleyballs and Nets",
      "Hockey Sticks, Pucks, and Nets",
      "Lacrosse Sticks and Balls",
    ],
    "Individual Sports Equipment": [
      "Tennis Rackets and Balls",
      "Golf Clubs and Balls",
      "Badminton Rackets and Shuttlecocks",
      "Table Tennis Tables and Paddles",
      "Squash Rackets and Balls",
    ],
    "Outdoor and Adventure Sports": [
      "Bicycles and Accessories",
      "Skateboards and Longboards",
      "Rollerblades and Ice Skates",
      "Climbing Gear (Harnesses, Ropes, Carabiners)",
      "Camping Equipment (Tents, Sleeping Bags)",
      "Surfboards",
      "Kayaks and Canoes",
    ],
    "Fitness Accessories": [
      "Fitness Trackers and Watches",
      "Heart Rate Monitors",
      "Gym Bags",
      "Water Bottles",
      "Towels",
      "Exercise Mats",
      "Sauna Suits",
      "Foam Rollers",
    ],
    Miscellaneous: [
      "Balance Boards",
      "Agility Ladders",
      "Hula Hoops",
      "Hand Exercisers",
      "Sliders",
      "Aerobic Steps",
    ],
  },
  condition: [
    "New",
    "Like new",
    "Refurbished",
    "Used - Excellent",
    "Used - Good",
    "Used - Fair",
    "For Parts or Not Working",
  ],
  brand: [
    "Not Specified",
    "Abu Garcia",
    "Adidas",
    "Adidas Boxing ",
    "AeroPilates by Stamina",
    "Align-Pilates",
    "Alo Yoga",
    "Altra",
    "Arc'teryx",
    "Arena",
    "Ashaway",
    "ASICS",
    "Asics",
    "Assault Fitness",
    "Atomic",
    "B Yoga",
    "Babolat",
    "Bad Boy ",
    "Balanced Body",
    "BASI Systems",
    "Bauer Hockey",
    "Bear Archery",
    "Berkley",
    "Bianchi",
    "Big Agnes",
    "Billabong",
    "Black Diamond",
    "Blind",
    "Body",
    "Body-Solid",
    "Boon ",
    "Bowflex",
    "Brine",
    "Brooks",
    "Burton",
    "Butterfly",
    "Callaway",
    "CamelBak",
    "Camp USA",
    "Cannondale",
    "Canterbury",
    "CAP Barbell ",
    "Carlton",
    "CCM Hockey",
    "Century",
    "Century Martial Arts ",
    "Cleto Reyes ",
    "Cleveland Golf",
    "Cobra",
    "Coleman",
    "Combat Sports ",
    "Concept2",
    "Cube",
    "Cybex",
    "Dagger",
    "Daiwa",
    "DHS (Double Happiness Sports)",
    "Diadora",
    "Donic",
    "Dunlop",
    "Easton",
    "Easton Hockey",
    "Edelrid",
    "Eleiko ",
    "Element",
    "Elina Pilates",
    "Enjoi",
    "Epoch Lacrosse",
    "Everlast",
    "Fairtex ",
    "Finis",
    "Fitbit",
    "Five Ten",
    "Force USA ",
    "G. Loomis",
    "Gaiam",
    "Garmin",
    "Giant",
    "Gilbert",
    "Girl",
    "Gnu",
    "Graf",
    "Gratz",
    "Gray-Nicolls",
    "GT Bicycles",
    "Gunn & Moore",
    "Gymshark",
    "Hammer Strength (Life Fitness) ",
    "Harbinger",
    "Hayabusa",
    "Head",
    "Hobie",
    "Hoist Fitness ",
    "Hoka One One",
    "Horizon Fitness",
    "Hoyt",
    "Hugger Mugger",
    "Hydro Flask",
    "Ironmaster ",
    "Jackson Kayaks",
    "Jade Yoga",
    "JBL",
    "Johnson Fitness",
    "Jones Snowboards",
    "JOOLA",
    "K2",
    "Kappa",
    "Karakal",
    "Keiser",
    "Kelty",
    "Killerspin",
    "Klean Kanteen",
    "Kookaburra",
    "Kurma Yoga",
    "La Sportiva",
    "Lews",
    "Lib Tech",
    "Life Fitness",
    "Li-Ning",
    "Lonsdale ",
    "Louisville Slugger",
    "Lululemon",
    "Mammut",
    "Manduka",
    "Marmot",
    "Marucci Sports",
    "Mathews",
    "Matrix Fitness",
    "Maverik Lacrosse",
    "Merida",
    "Merrell",
    "Metolius",
    "Michael Phelps (MP)",
    "Mikasa",
    "Mitre",
    "Mizuno",
    "Molten",
    "MSR (Mountain Safety Research)",
    "Nautilus",
    "New Balance",
    "Nike",
    "Nitro",
    "NordicTrack",
    "Oakley",
    "Ocean Kayak",
    "Octane Fitness",
    "Old Town Canoe",
    "O'Neill",
    "Oov",
    "Orvis",
    "Osprey",
    "Patagonia",
    "Peak Pilates",
    "Peloton",
    "Penn",
    "Perception Kayaks",
    "Petzl",
    "Pilates Designs by Basil",
    "Pinarello",
    "Ping",
    "Plan B",
    "Polar",
    "Powertec ",
    "PrAna",
    "Precor",
    "Prince",
    "ProForm",
    "PSE Archery",
    "Puma",
    "Quiksilver",
    "Rapala",
    "Rawlings",
    "RDX Sports ",
    "Reebok",
    "REI Co-op",
    "Revgear ",
    "Riddell",
    "Ringside ",
    "Rip Curl",
    "Rogue Fitness",
    "Rossignol",
    "Salomon",
    "Samick Sports",
    "Santa Cruz",
    "Saucony",
    "Scarpa",
    "Schutt",
    "Schwinn Fitness",
    "Scott",
    "Scramble ",
    "Sherwood",
    "Shimano",
    "Skullcandy",
    "Sole Fitness",
    "Spalding",
    "Spartan Sports",
    "Specialized",
    "Speedo",
    "Srixon",
    "SS (Sareen Sports Industries)",
    "St. Croix",
    "StairMaster",
    "STIGA",
    "Stott Pilates (Merrithew)",
    "STX",
    "Sunny Health & Fitness",
    "S'well",
    "Tachikara",
    "Tatami Fightwear ",
    "TaylorMade",
    "Technogym",
    "Tecnifibre",
    "Tecnifibre",
    "The North Face",
    "Theraband",
    "Titan Fitness ",
    "Title Boxing ",
    "Titleist",
    "Tone It Up",
    "Top King ",
    "Trek",
    "TriggerPoint",
    "True Temper Sports",
    "TuffStuff Fitness ",
    "Twins Special",
    "TYR",
    "Umbro",
    "Under Armour",
    "Venum",
    "Victor",
    "Volkl",
    "Vulcan Strength ",
    "Warrior Sports",
    "Weider ",
    "Wilson",
    "Wilson /DeMarini",
    "Wilson Staff",
    "Winning ",
    "Woodway",
    "Xenith",
    "Xiom",
    "YETI",
    "Yogitoes",
    "Yonex",
    "York Barbell ",
    "Zero",
    "Zoggs",
  ],
  gender: [
    "Not Specified",
    "Adults",
    "Teens",
    "Children",
    "0-3 Years (Toddlers)",
    "4-7 Years (Young Children)",
    "8-12 Years (Preteens)",
    "Seniors",
    "Infants",
  ],
  sellerType: [
    "Not Specified",
    "Private Seller",
    "Dealer",
    "Retailer/Store",
    "Distributor",
    "Manufacturer",
    "Wholesaler",
    "Non-Profit or Community Group",
    "Liquidator",
    "Government",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
