export const selectData = {
  category: {
    Tops: [
      "T-Shirts",
      "Blouses",
      "Sweaters & Knitwear",
      "Tank Tops",
      "Hoodies & Sweatshirts",
      "Shirts",
      "Tunics",
      "Bodysuits",
      "Bodysuits",
      "Camisoles",
    ],
    Bottoms: [
      "Jeans",
      "Pants",
      "Shorts",
      "Skirts",
      "Activewear Bottoms",
      "Trousers",
      "Dress Bottoms",
      "Jumpsuits & Overalls",
    ],
    Dresses: [
      "Casual Dresses",
      "Formal Dresses",
      "Work Dresses",
      "Summer Dresses",
      "Party Dresses",
      "Maxi Dresses",
      "Mini Dresses",
      "Midi Dresses",
      "Winter Dresses",
      "Maternity Dresses",
      "Vintage Dresses",
    ],
    "Children's Wear": [
      "Baby (0-24 months)",
      "Toddler (2-4 years)",
      "Kids (5-12 years)",
      "Teens (13-18 years)",
      "Seasonal Collections",
      "Occasion Wear",
      "Eco-Friendly and Organic Wear",
      "School Uniforms",
      "Character and Theme Wear",
    ],
    Outerwear: [
      "Coats",
      "Jackets",
      "Vests",
      "Rainwear",
      "Snow & Ski Wear",
      "Fleece",
      "Insulated Jackets",
      "Softshell Jackets",
      "Technical Outerwear",
      "Capes & Shawls",
    ],
    "Active Wear": [
      "Tops",
      "Bottoms",
      "Outerwear",
      "Sports Specific Gear",
      "Accessories",
    ],
    Footwear: [
      "Sneakers",
      "Boots",
      "Dress Shoes",
      "Sandals",
      "Flats",
      "Heels",
      "Athletic Shoes",
      "Outdoor Shoes",
      "Slippers",
      "Specialty Footwear",
    ],
    "Plus Size Clothing": [
      "Tops",
      "Bottoms",
      "Dresses",
      "Outerwear",
      "Activewear",
      "Swimwear",
      "Lingerie",
      "Loungewear",
      "Maternity Wear",
    ],
    Accessories: [
      "Bags & Wallets",
      "Belts",
      "Hats",
      "Scarves & Wraps",
      "Sunglasses",
      "Jewelry",
      "Watches",
      "Hair Accessories",
      "Tech Accessories",
      "Gloves",
      "Socks & Hosiery",
      "Eyewear",
      "Umbrellas",
      "Keychains",
    ],
    "Bags and Purses": [
      "Handbags",
      "Purses",
      "Travel Bags",
      "Backpacks",
      "Specialty Bags",
      "Business Bags",
      "Luxury Handbags",
      "Eco-Friendly Bags",
      "Artisan and Handmade",
      "Vintage Bags",
    ],
    "Lingerie and Sleepwear": [
      "Bras",
      "Panties",
      "Lingerie Sets",
      "Shapewear",
      "Camisoles and Tanks",
      "Corsets and Bustiers",
      "Hosiery and Garters",
      "Pajama Sets",
      "Nightgowns and Sleep Shirts",
      "Robes",
      "Loungewear",
      "Slippers",
      "Sleepwear Accessories",
    ],
    Swimwear: [
      "One-Piece Swimsuits",
      "Bikinis",
      "Tankinis",
      "Swim Trunks",
      "Rash Guards",
      "Cover-Ups",
      "Swimwear for Kids",
      "Competitive Swimwear",
      "Swim Accessories",
      "Plus Size Swimwear",
      "Maternity Swimwear",
    ],
    "Formal Wear": [
      "Suits",
      "Blazers & Sport Coats",
      "Formal Trousers",
      "Formal Shirts",
      "Waistcoats",
      "Accessories",
      "Evening Gowns",
      "Cocktail Dresses",
      "Suits & Blazers",
      "Formal Skirts",
      "Formal Tops & Blouses",
      "Accessories",
      "Outerwear",
      "Traditional & Cultural Attire",
    ],
    "Maternity Wear": [
      "Tops",
      "Dresses",
      "Bottoms",
      "Outerwear",
      "Lingerie & Sleepwear",
      "Swimwear",
      "Activewear",
      "Accessories",
    ],
    "Ethnic Wear": [
      "Dresses & Robes",
      "Skirts and Blouses",
      "Pants and Tunics",
      "Formal Ethnic Wear",
      "Casual Ethnic Wear",
      "Outerwear",
      "Headwear",
      "Children’s Ethnic Wear",
      "Accessories",
      "Shoes",
    ],
    "Uniforms and Workwear": [
      "Healthcare Uniforms",
      "Hospitality & Service",
      "Industrial & Construction",
      "Corporate Wear",
      "School Uniforms",
      "Security Uniforms",
      "Sports & Team Wear",
      "Beauty & Health Spa",
      "Aviation Uniforms",
      "Transport & Logistics",
      "Accessories",
    ],
    "Vintage Clothing": [
      "1920s: Flapper dresses, cloche hats",
      "1930s: Bias-cut gowns, fedoras",
      "1940s: Utility clothing, A-line skirts",
      "1950s: Swing dresses, pencil skirts",
      "1960s: Mod dresses, go-go boots",
      "1970s: Bell-bottoms, maxi dresses",
      "1980s: Power suits, neon clothing",
      "1990s: Grunge flannel, slip dresses",
      "Rockabilly: 1950s",
      "Bohemian: 1970s",
      "Punk: 1970s",
      "Mod: 1960s",
      "Hats",
      "Jewelry",
      "Bags",
      "Scarves and Gloves",
      "Shoes",
    ],
    "Sustainable and Eco-Friendly Fashion": [
      "Organic Materials",
      "Recycled and Upcycled",
      "Eco-Friendly Production",
      "Vegan and Cruelty-Free",
      "Fair Trade",
      "Locally Made",
      "Slow Fashion",
      "Zero Waste",
      "Biodegradable",
      "Rentals and Swaps",
      "Handmade",
      "Sustainable Accessories",
    ],
  },
  size: {
    Tops: ["XS", "S", "M", "L", "XL", "XXL"],
    Bottoms: ["XS", "S", "M", "L", "XL", "XXL"],
    Dresses: ["XS", "S", "M", "L", "XL", "XXL"],
    "Children's Wear": [
      "0-3 months",
      "3-6 months",
      "6-12 months",
      "12-24 months",
      "2-4 years",
      "5-7 years",
      "8-10 years",
      "11-12 years",
      "13-14 years",
      "15-16 years",
    ],
    Outerwear: ["XS", "S", "M", "L", "XL", "XXL"],
    "Active Wear": ["XS", "S", "M", "L", "XL", "XXL"],
    Footwear: [
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "37",
      "37.5",
      "38",
      "38.5",
      "39",
      "40",
      "41",
      "41.5",
      "42",
      "42.5",
      "43",
      "44",
      "44.5",
    ],
    "Plus Size Clothing": ["1X", "2X", "3X", "4X", "5X", "6X"],
    "Lingerie and Sleepwear": ["XS", "S", "M", "L", "XL", "XXL"],
    Swimwear: ["XS", "S", "M", "L", "XL", "XXL"],
    "Formal Wear": ["XS", "S", "M", "L", "XL", "XXL"],
    "Maternity Wear": ["XS", "S", "M", "L", "XL", "XXL"],
    "Ethnic Wear": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "Child S",
      "Child M",
      "Child L",
    ],
    Shoes: [
      "5 (W)",
      "6 (W)",
      "7 (W)",
      "8 (W)",
      "9 (W)",
      "10 (W)",
      "11 (W)",
      "5 (M)",
      "6 (M) ",
      "7 (M)",
      "8 (M)",
      "9 (M)",
      "10 (M)",
      "11 (M)",
      "12 (M)",
      "13 (M)",
    ],
    "Uniforms and Workwear": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    "Vintage Clothing": ["XXS", "XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    "Sustainable and Eco-Friendly Fashion": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
    ],
  },
  gender: ["Men's", "Women's", "Unisex", "Children's"],

  condition: ["New", "Like-new", "Used item"],
  color: [
    "Not Specified",
    "Black",
    "White",
    "Gray",
    "Silver",
    "Gold",
    "Beige",
    "Ivory",
    "Tan",
    "Brown",
    "Maroon",
    "Red",
    "Burgundy",
    "Pink",
    "Rose",
    "Magenta",
    "Purple",
    "Lavender",
    "Violet",
    "Indigo",
    "Blue",
    "Navy",
    "Teal",
    "Turquoise",
    "Cyan",
    "Green",
    "Olive",
    "Lime",
    "Yellow",
    "Amber",
    "Orange",
    "Coral",
    "Peach",
    "Apricot",
    "Neon Colour",
    "Metallic Colour",
    "Multicolour",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  material: [
    "Not Specified",
    "Cotton",
    "Wool",
    "Silk",
    "Linen",
    "Polyester",
    "Nylon",
    "Rayon",
    "Denim",
    "Leather",
    "Suede",
    "Velvet",
    "Chiffon",
    "Lace",
    "Jersey",
    "Spandex/Lycra",
    "Acrylic",
    "Tweed",
    "Corduroy",
    "Bamboo",
    "Hemp",
    "Tencel/Lyocell",
    "Organza",
    "Brocade",
    "Satin",
    "Flannel",
    "Microfiber",
    "Neoprene",
    "Gore-Tex",
    "Cashmere",
    "Alpaca",
  ],
  sellerType: ["Not Specified", "Private", "Commercial seller"],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
