export const selectData = {
  gender: ["Men's", "Women's", "Unisex", "Children's"],

  condition: ["New", "Like-new", "Used item"],
  color: [
    "Not Specified",
    "Black",
    "White",
    "Gray",
    "Silver",
    "Gold",
    "Beige",
    "Ivory",
    "Tan",
    "Brown",
    "Maroon",
    "Red",
    "Burgundy",
    "Pink",
    "Rose",
    "Magenta",
    "Purple",
    "Lavender",
    "Violet",
    "Indigo",
    "Blue",
    "Navy",
    "Teal",
    "Turquoise",
    "Cyan",
    "Green",
    "Olive",
    "Lime",
    "Yellow",
    "Amber",
    "Orange",
    "Coral",
    "Peach",
    "Apricot",
    "Neon Colour",
    "Metallic Colour",
    "Multicolour",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  material: [
    "Not Specified",
    "Cotton",
    "Wool",
    "Silk",
    "Linen",
    "Polyester",
    "Nylon",
    "Rayon",
    "Denim",
    "Leather",
    "Suede",
    "Velvet",
    "Chiffon",
    "Lace",
    "Jersey",
    "Spandex/Lycra",
    "Acrylic",
    "Tweed",
    "Corduroy",
    "Bamboo",
    "Hemp",
    "Tencel/Lyocell",
    "Organza",
    "Brocade",
    "Satin",
    "Flannel",
    "Microfiber",
    "Neoprene",
    "Gore-Tex",
    "Cashmere",
    "Alpaca",
  ],
  sellerType: ["Not Specified", "Private", "Commercial seller"],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
