export const selectData = {
  type: [
    "Single-Family Home",
    "Condominium (Condo)",
    "Apartment/Flat",
    "Townhouse",
    "Duplex/Triplex",
    "Multi-Family Home",
    "Loft",
    "Co-op (Housing Cooperative)",
    "Mobile/Manufactured Home",
    "Farm/Ranch",
    "Villa",
    "Penthouse",
    "Land",
  ],
  bedrooms: [
    "Studio",
    "1 Bedroom",
    "2 Bedrooms",
    "3 Bedrooms",
    "4 Bedrooms",
    "5+ Bedrooms",
  ],
  bathrooms: [
    "1 Bathroom",
    "1.5 Bathrooms",
    "2 Bathrooms",
    "2.5 Bathrooms",
    "3 Bathrooms",
    "3.5 Bathrooms and Above",
    "4+ Bathrooms",
  ],
  // built: [],
  // plot: [],
  tenure: [],
  condition: [
    "Brand New",
    "Less than 5 years old",
    "5-10 years old",
    "10-20 years old",
    "20-50 years old",
    "Over 50 years old",
    "Historic/Heritage (100+ years)",
  ],
  year: [
    "Brand New",
    "Less than 5 years old",
    "5-10 years old",
    "10-20 years old",
    "20-50 years old",
    "Over 50 years old",
    "Historic/Heritage (100+ years)",
  ],
  energy: [
    "ENERGY STAR Certified",
    "LEED Certification",
    "HERS Index Score",
    "Net-Zero Energy",
    "Green Building Certification",
    "High-Efficiency Appliances Included",
    "Solar Panels Installed",
    "Smart Home Features",
    "Insulation and Windows",
    "Electric Vehicle Charging Station",
    "A-Rated",
    "B-Rated",
    "C-Rated",
    "D-Rated",
    "E-Rated",
    "F-Rated",
    "G-Rated",
    "A Rating",
    "B Rating",
    "C Rating",
    "D Rating",
    "E Rating",
    "F Rating",
    "G Rating",
    "Not Available/Not Applicable",
  ],
  nearest: [
    "Shopping Centers/Malls",
    "Parks and Recreational Areas",
    "Schools and Educational Institutions",
    "Public Transport Hubs",
    "Restaurants and Entertainment Districts",
    "Historical Sites and Cultural Attractions",
    "Hospitals and Medical Facilities",
    "Business Districts/Corporate Centers",
    "Beaches or Waterfronts",
    "Sports Facilities and Stadiums",
    "Airports",
  ],
  facilities: [
    "Parking",
    "Outdoor Space",
    "Swimming Pool",
    "Fitness Center/Gym",
    "Elevator",
    "Security Features",
    "Air Conditioning/Heating System",
    "Laundry Facilities",
    "Pet-Friendly Amenities",
    "Storage Space",
    "Internet/High-Speed Connectivity",
    "Disabled Access",
    "Children's Play Area",
    "Community Spaces",
    "Eco-Friendly Features",
    "Recreational Facilities",
    "Public Transportation Access",
    "Concierge Services",
  ],

  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
