export const selectData = {
  type: {
    "Home Services": [
      "Cleaning Services",
      "Home Repair",
      "Landscaping and Gardening",
      "Interior Design and Decoration",
      "Pest Control",
      "Moving and Storage",
      "Home Security Installation",
    ],
    Childcare: [
      "Babysitting",
      "Nanny Services",
      "Au Pair Services",
      "Daycare Services",
      "After-School Programs",
      "Special Needs Childcare",
      "Tutoring Services",
      "Child Transportation Services",
      "Holiday Camps and Workshops",
      "Parent’s Helper",
      "Childminding Services",
      "Early Childhood Education Services",
      "Emergency Childcare Services",
      "Night Nurse/Newborn Care Services",
      "Playgroup and Social Group Organizing",
    ],
    "Educational Services": [
      "Tutoring",
      "Language Instruction",
      "Music Lessons",
      "Art and Craft Workshops",
      "Cooking Classes",
      "Professional Development",
    ],
    "Health and Wellness": [
      "Personal Training",
      "Nutrition and Diet Planning",
      "Massage Therapy",
      "Mental Health Services",
      "Alternative Therapies",
    ],
    "Beauty and Personal Care": [
      "Hair Styling and Salon Services",
      "Makeup and Beauty Services",
      "Spa Treatments",
      "Fashion and Image Consulting",
    ],
    "Events and Entertainment": [
      "Event Planning",
      "Music and DJ Services",
      "Photography and Videography",
      "Catering Services",
      "Performers and Artists",
    ],
    "Technical and Digital Services": [
      "Web Design and Development",
      "Graphic Design",
      "Digital Marketing",
      "IT and Computer Repair",
    ],
    "Recreational Experiences": [
      "Adventure Activities",
      "Workshops and Classes",
      "Travel and Tour Services",
      "Culinary Experiences",
      "Sports Coaching",
    ],
    "Business Services": [
      "Consulting Services",
      "Legal Services",
      "Accounting and Tax Services",
      "Real Estate Services",
    ],
    "Pet Services": [
      "Pet Grooming",
      "Pet Sitting and Walking",
      "Veterinary Services",
      "Pet Training",
    ],
    "Miscellaneous Services": [
      "Vehicle Services",
      "Tailoring and Alterations",
      "Translation and Interpretation",
      "Craft and DIY Services",
      "Other Services",
    ],
  },
  providerType: [
    "Individuals",
    "Professionals",
    "Businesses/Companies",
    "Non-Profits",
    "Government Entities",
    "Freelancers",
    "Agencies",
    "Local Artisans/Craftsmen",
    "Online/Virtual Service Providers",
    "Community Groups/Volunteers",
  ],
  licenses: [
    "Licensed Professional",
    "Certified Expert",
    "Bonded",
    "Insured",
    "Accredited",
    "Degree Holder",
    "Member of Professional Association",
    "Health and Safety Certifications",
    "CPR/First Aid Certified",
    "Specialized Training",
    "Background Checked",
    "Other Certifications",
  ],
  cancellationPolicy: [
    "Not Specified",
    "Flexible",
    "Moderate",
    "Strict",
    "24-Hour Cancellation",
    "48-Hour Cancellation",
    "7-Day Cancellation",
    "No Refunds",
    "Custom Cancellation Policies",
    "Full Refund",
    "Partial Refund",
    "Credit for Future Service",
    "Non-Refundable Deposit",
  ],
};
