export const selectData = {
  brand: [
    "MAC Cosmetics",
    "Maybelline",
    "L'Oréal Paris",
    "NARS",
    "Urban Decay",
    "Too Faced",
    "Fenty Beauty by Rihanna",
    "Anastasia Beverly Hills",
    "Tarte Cosmetics",
    "Revlon",
    "Estée Lauder",
    "Clinique",
    "Dior Makeup",
    "Chanel",
    "Charlotte Tilbury",
    "Bobbi Brown",
    "Huda Beauty",
    "NYX Professional Makeup",
    "Smashbox",
    "BareMinerals",
    "Benefit Cosmetics",
    "Stila Cosmetics",
    "Laura Mercier",
    "Kat Von D Beauty (now KVD Vegan Beauty)",
    "Sephora Collection",
    "Morphe",
    "Glossier",
    "ELF Cosmetics",
    "ColourPop",
    "IT Cosmetics",
    "Pantene",
    "Tresemmé",
    "Head & Shoulders",
    "Garnier Fructis",
    "L'Oréal Paris",
    "Herbal Essences",
    "Dove",
    "Schwarzkopf",
    "Aussie",
    "Sunsilk",
    "Redken",
    "Kérastase",
    "Paul Mitchell",
    "Moroccanoil",
    "Aveda",
    "Olaplex",
    "Wella Professionals",
    "Joico",
    "Pureology",
    "Matrix",
    "Avalon Organics",
    "Briogeo",
    "SheaMoisture",
    "Alba Botanica",
    "Giovanni",
    "John Masters Organics",
    "Rahua",
    "Acure",
    "Desert Essence",
    "Weleda",
    "Oribe",
    "Christophe Robin",
    "Bumble and bumble",
    "Sisley Paris",
    "Alterna Haircare",
    "R+Co",
    "Living Proof",
    "Philip B",
    "Davines",
    "Frederic Fekkai",
    "DevaCurl ",
    "The Mane Choice ",
    "Carol's Daughter ",
    "Nioxin ",
    "OGX ",
    "Mielle Organics ",
    "Cantu ",
    "Tangle Teezer ",
    "Kinky-Curly ",
    "Pattern by Tracee Ellis Ross ",
    "Chanel",
    "Dior",
    "Gucci",
    "Yves Saint Laurent",
    "Prada",
    "Versace",
    "Dolce & Gabbana",
    "Armani",
    "Burberry",
    "Hermès",
    "Calvin Klein",
    "Elizabeth Arden",
    "Marc Jacobs",
    "Ralph Lauren",
    "Tommy Hilfiger",
    "Hugo Boss",
    "Davidoff",
    "Jean Paul Gaultier",
    "Lancôme",
    "Estée Lauder",
    "Creed",
    "Jo Malone London",
    "Diptyque",
    "Byredo",
    "Le Labo",
    "Amouage",
    "Tom Ford Private Blend",
    "Serge Lutens",
    "Frederic Malle",
    "Penhaligon's",
    "Jennifer Lopez",
    "Britney Spears",
    "David Beckham",
    "Sarah Jessica Parker",
    "Paris Hilton",
    "Rihanna",
    "Kim Kardashian",
    "Justin Bieber",
    "Katy Perry",
    "Lady Gaga",
    "Coty",
    "Revlon",
    "Avon",
    "L'Oréal",
    "Yardley London",
    "Dove",
    "Old Spice",
    "Nautica",
    "Axe",
    "Elizabeth Taylor",
    "Gillette",
    "The Art of Shaving",
    "Bevel",
    "Dollar Shave Club",
    "Harry’s",
    "Braun",
    "Philips Norelco",
    "Proraso",
    "Jack Black",
    "Bulldog Skincare",
    "Kiehl’s Men",
    "Clinique for Men",
    "Lab Series",
    "L'Oréal Men Expert",
    "Nivea Men",
    "Biotherm Homme",
    "Brickell Men’s Products",
    "Anthony Skincare",
    "Baxter of California",
    "Cetaphil Men",
    "American Crew",
    "Old Spice",
    "Dove Men+Care",
    "Aveda Men Pure-Formance™",
    "Redken Brews",
    "Hanz de Fuko",
    "Schwarzkopf",
    "Paul Mitchell",
    "Head & Shoulders Men",
    "TIGI Bed Head for Men",
    "Calvin Klein",
    "Hugo Boss",
    "Giorgio Armani",
    "Dolce & Gabbana",
    "Ralph Lauren",
    "Paco Rabanne",
    "Davidoff",
    "Versace",
    "Tom Ford",
    "Yves Saint Laurent",
    "Burt's Bees",
    "Weleda",
    "Dr. Hauschka",
    "Jurlique",
    "Sukin",
    "Origins ",
    "Korres",
    "REN Clean Skincare",
    "Pai Skincare",
    "Eminence Organic Skin Care",
    "Aveda",
    "Rahua",
    "John Masters Organics",
    "Yarok",
    "SheaMoisture",
    "Acure Organics",
    "Briogeo",
    "Desert Essence",
    "Giovanni Cosmetics",
    "Innersense Organic Beauty",
    "Ilia Beauty",
    "RMS Beauty",
    "W3ll People",
    "Jane Iredale",
    "Vapour Organic Beauty",
    "100% Pure",
    "Ere Perez",
    "Alima Pure",
    "Juice Beauty",
    "Zuii Organic",
    "Alba Botanica",
    "Dr. Bronner's",
    "Lush ",
    "Neal's Yard Remedies",
    "The Body Shop ",
    "Herbivore Botanicals",
    "Soapwalla",
    "Puracy",
    "Caudalie",
    "Natura Brasil",
    "Ursa Major",
    "Bulldog Skincare",
    "Jack Black ",
    "Brickell Men’s Products",
    "Badger Balm",
    "The Art of Shaving ",
    "Aesop",
    "Every Man Jack",
    "Proraso ",
    "Anthony ",
    "Other Brand",
  ],
  condition: ["New", "Used", "Refurbished"],
  gender: ["Women", "Men", "Unisex", "Children", "Teens", "No Preference"],
  skin: [
    "Normal",
    "Oily",
    "Dry",
    "Combination",
    "Sensitive",
    "Mature",
    "Acne-Prone",
    "All Skin Types",
    "Straight",
    "Wavy",
    "Curly",
    "Coily/Kinky",
    "Thin/Fine",
    "Thick",
    "Dry/Damaged",
    "Oily",
    "Color-Treated",
    "Normal",
    "All Hair Types",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  ingredients: [
    "Vegan",
    "Cruelty-Free",
    "Hypoallergenic",
    "Non-comedogenic",
    "Aloe Vera",
    "Charcoal",
    "Hyaluronic Acid",
    "Salicylic Acid",
    "Retinol",
    "Tea Tree Oil",
    "Glycerin",
    "Eco-Friendly Packaging",
    "Fair Trade Ingredients",
  ],
  size: [
    "Under 50 ml / 1.7 oz (Travel Size, Sample Size)",
    "50 ml / 1.7 oz - 100 ml / 3.4 oz (Standard Small Size)",
    "100 ml / 3.4 oz - 250 ml / 8.5 oz (Standard Size)",
    "250 ml / 8.5 oz - 500 ml / 17 oz (Large Size)",
    "Over 500 ml / 17 oz (Bulk Size)",
    "Under 50 g / 1.8 oz (Travel Size, Sample Size)",
    "50 g / 1.8 oz - 100 g / 3.5 oz (Standard Small Size)",
    "100 g / 3.5 oz - 250 g / 8.8 oz (Standard Size)",
    "250 g / 8.8 oz - 500 g / 17.6 oz (Large Size)",
    "Over 500 g / 17.6 oz (Bulk Size)",
    "Single Item / Single Use",
    "Pack of 2-5",
    "Pack of 6-10",
    "Pack of 11-20",
    "Pack of 21 or more",
    "Mini Set (Travel Kit, Sample Kit)",
    "Standard Set",
    "Deluxe/Large Set",
  ],
  certifications: [
    "Cruelty-free",
    "Organic",
    "Vegan",
    "Natural Ingredients",
    "Fair Trade",
    "Gluten-Free",
    "Non-GMO",
    "Hypoallergenic",
    "Halal",
    "Kosher",
    "Paraben-Free",
    "Sulfate-Free",
    "Dermatologically Tested",
    "Eco-Friendly Packaging",
    "Eco-Friendly Packaging",
  ],

  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
