export const selectData = {
  type: [
    "House/Detached House",
    "Semi-Detached House",
    "Terraced House",
    "Flat/Apartment",
    "Maisonette",
    "Bungalow",
    "Cottage",
    "Mobile Home/Static Caravan",
    "Studio/Studio Flat",
    "Loft/Loft Apartment",
    "Duplex",
    "Farmhouse",
    "Land/Plot",
    "Office Space",
    "Retail Premises/Shop",
    "Industrial Unit",
    "Warehouse",
    "Mixed-Use Property",
    "Cooperative Housing (Co-op)",
    "Mansion/Manor House",
    "Penthouse",
    "Holiday Home/Vacation Home",
    "Shared Housing/House Share",
  ],
  bedrooms: [
    "Studio",
    "1 Bedroom",
    "2 Bedrooms",
    "3 Bedrooms",
    "4 Bedrooms",
    "5+ Bedrooms",
  ],
  bathrooms: ["1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5+"],
  propertySize: [
    "Not Specified",
    "Under 500 sq ft (Under 46 sq m)",
    "500 - 999 sq ft (46 - 92 sq m)",
    "1,000 - 1,499 sq ft (93 - 139 sq m)",
    "1,500 - 1,999 sq ft (140 - 185 sq m)",
    "2,000 - 2,499 sq ft (186 - 231 sq m)",
    "2,500 - 2,999 sq ft (232 - 278 sq m)",
    "3,000 - 3,499 sq ft (279 - 324 sq m)",
    "3,500 - 3,999 sq ft (325 - 371 sq m)",
    "4,000 - 4,499 sq ft (372 - 418 sq m)",
    "4,500 - 4,999 sq ft (419 - 464 sq m)",
    "5,000 sq ft and over (465 sq m and over)",
  ],
  lotSize: [
    "Not Specified",
    "Under 0.25 acres (Under 0.1 hectares)",
    "0.25 - 0.49 acres (0.1 - 0.19 hectares)",
    "0.5 - 0.99 acres (0.2 - 0.39 hectares)",
    "1 - 1.99 acres (0.4 - 0.79 hectares)",
    "2 - 4.99 acres (0.8 - 2.01 hectares)",
    "5 - 9.99 acres (2.02 - 4.04 hectares)",
    "10 - 19.99 acres (4.05 - 8.09 hectares)",
    "20 - 49.99 acres (8.1 - 20.23 hectares)",
    "50 - 99.99 acres (20.24 - 40.46 hectares)",
    "100 acres and over (40.47 hectares and over)",
  ],
  ownership: [
    "Not Specified",
    "Freehold",
    "Leasehold",
    "Commonhold",
    "Co-op",
    "Share of Freehold",
  ],
  condition: [
    "Not Specified",
    "New Construction",
    "Excellent",
    "Good",
    "Fair",
    "Needs Work",
    "Fixer-Upper",
  ],
  year: [
    "Not Specified",
    "Before 1900",
    "1900 - 1949",
    "1950 - 1969",
    "1970 - 1989",
    "1990 - 1999",
    "2000 - 2009",
    "2010 - 2015",
    "2016 - Present",
  ],
  lease: [
    "Not Specified",
    "Short-Term (Less than 6 months)",
    "6 Months",
    "1 Year",
    "18 Months",
    "2 Years",
    "Flexible Lease Terms",
    "Rent to Own",
  ],
  parking: [
    "Not Specified",
    "On-Street Parking",
    "Off-Street Parking",
    "Covered Parking",
    "Private Garage",
    "Shared Garage",
    "Underground Parking",
    "Gated Parking",
    "Assigned Parking",
    "Visitor Parking",
    "EV Charging Stations",
    "Bicycle Parking",
    "RV Parking",
  ],
  amenities: [
    "Not Specified",
    "Swimming Pool",
    "Fitness Center / Gym",
    "Spa / Sauna",
    "Rooftop Terrace",
    "Garden / Courtyard",
    "BBQ Area",
    "Playground / Kids' Area",
    "Sports Courts (Tennis, Basketball, etc.)",
    "Golf Course Access",
    "Clubhouse / Community Center",
    "Business Center / Co-working Space",
    "Conference / Meeting Rooms",
    "Theater Room",
    "Game Room / Arcade",
    "Library / Study Room",
    "Pet-Friendly Features (e.g., Dog Park)",
    "Walking / Biking Trails",
    "On-site Laundry Facilities",
    "In-unit Washer and Dryer",
    "Air Conditioning / Central Heating",
    "High-speed Internet Access",
    "Cable Ready",
    "Smart Home Features",
    "Security System / Gated Access",
    "Concierge Service",
    "Parking (Covered, Garage, Reserved)",
    "EV Charging Stations",
    "Bicycle Storage",
    "Storage Units",
    "Green Certifications (LEED, Energy Star, etc.)",
    "Waterfront / Beach Access",
    "Balcony / Patio",
    "Elevator Access",
  ],

  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
