export const selectData = {
  condition: [
    "New",
    "Like New",
    "Excellent",
    "Good",
    "Fair",
    "Poor",
    "For Parts or Not Working",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  age: [
    "Not Specified",
    "Brand New",
    "Less than 1 year old",
    "1 - 3 years old",
    "3 - 5 years old",
    "5 - 10 years old",
    "10 - 20 years old",
    "Over 20 years old",
  ],
  brand: [
    "Not Specified",
    "Fender",
    "Gibson",
    "Ibanez",
    "Martin",
    "Taylor",
    "Yamaha",
    "PRS (Paul Reed Smith)",
    "Epiphone",
    "ESP",
    "Jackson",
    "Rickenbacker",
    "Gretsch",
    "Steinway & Sons",
    "Kawai",
    "Casio",
    "Fazioli",
    "Roland",
    "Bosendorfer",
    "Nord",
    "Kurzweil",
    "Moog",
    "Pearl",
    "Ludwig",
    "Tama",
    "DW (Drum Workshop)",
    "Zildjian",
    "Sabian",
    "Roland",
    "Gretsch Drums",
    "Mapex",
    "Selmer",
    "Bach",
    "Conn",
    "Buffet Crampon",
    "Jupiter",
    "Vandoren",
    "D'Addario",
    "Stradivarius",
    "Stentor",
    "Cecilio",
    "Hohner",
    "Pearl River",
    "Suzuki",
    "ROLI",
    "Meinl",
    "Other brand",
  ],
  sellerType: [
    "Not Specified",
    "Individual/Private Seller",
    "Music Store/Retailer",
    "Authorized Dealer",
    "Luthier/Builder",
    "Wholesaler/Distributor",
    "Educational Institution",
    "Rental Company",
    "Consignment Seller",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
  type: {
    "String Instruments": [
      "Violin",
      "Viola",
      "Cello",
      "Double Bass",
      "Guitar",
      "Harp",
      "Ukulele",
      "Banjo",
      "Mandolin",
      "Lute",
    ],
    "Woodwind Instruments": [
      "Flute",
      "Clarinet",
      "Oboe",
      "Bassoon",
      "Saxophone",
      "Recorder",
      "Piccolo",
      "Bass Clarinet",
      "English Horn",
    ],
    "Brass Instruments": [
      "Trumpet",
      "Trombone",
      "French Horn",
      "Tuba",
      "Euphonium",
      "Cornet",
      "Flugelhorn",
    ],
    "Percussion Instruments": [
      "Drum Kit",
      "Timpani",
      "Xylophone",
      "Marimba",
      "Vibraphone",
      "Conga",
      "Bongo",
      "Djembe",
      "Cajon",
      "Tambourine",
      "Maracas",
      "Snare Drum",
      "Bass Drum",
    ],
    "Keyboard Instruments": [
      "Piano",
      "Organ",
      "Synthesizer",
      "Keyboard",
      "Harpsichord",
      "Accordion",
      "Melodica",
    ],
    "Electronic Instruments": [
      "Electric Guitar",
      "Electric Bass",
      "Synthesizer",
      "Drum Machine",
      "Electronic Keyboard",
      "MIDI Controller",
      "Theremin",
    ],
    "Folk and World Instruments": [
      "Sitar",
      "Tabla",
      "Harmonium",
      "Bouzouki",
      "Didgeridoo",
      "Erhu",
      "Oud",
      "Balalaika",
      "Koto",
      "Shamisen",
      "Accordion",
    ],
    "Other Instruments": [
      "Voice (Singing)",
      "Turntables (DJ equipment)",
      "Electronic effects and loopers",
      "Other",
    ],
  },
};
