export const selectData = {
  category: ["All", "Pets for sale", "Pets for adoption", "Pet Supplies"],
  subCategory: {
    "Pets for sale": [
      "Dogs",
      "Cats",
      "Birds",
      "Fish",
      "Reptile",
      "Rabbits",
      "Rodents",
      "Livestock",
      "Horses",
      "Amphibian",
    ],

    "Pets for adoption": [
      "Dogs",
      "Cats",
      "Birds",
      "Fish",
      "Reptile",
      "Rabbits",
      "Rodents",
      "Livestock",
      "Horses",
      "Amphibian",
    ],

    "Pet Supplies": [
      "Food",
      "Treats  & Edible Chews",
      "Toys & Apparel",
      "Grooming & Pet Health",
      "Supplies",
      "Flea & Tick Control",
      "Shops",
    ],
  },
  filters: {
    dogs: {
      breed: [
        "Affenpinscher",
        "Afghan Hound",
        "Airedale Terrier ",
        "Akita",
        "Alapaha Blue Blood Bulldog",
        "Alaskan Malamute",
        "American Bulldog",
        "American Bully ",
        "American Cocker Spaniel",
        "American Hairless Terrier",
        "American Pocket Bullie",
        "Anatolian Shepherd ",
        "Australian Cattle Dog",
        "Australian Kelpie ",
        "Australian Shepherd",
        "Australian Silky Terrier",
        "Australian Terrier",
        "Basenji",
        "Basset Bleu De Gascogne",
        "Basset Fauve De Bretagne",
        "Basset Griffon Vendeen",
        "Basset Hound",
        "Bavarian Mountain Hound",
        "Beagle",
        "Bearded Collie",
        "Beauceron",
        "Bedlington Terrier",
        "Belgian Shepherd",
        "Bergamasco",
        "Bernese Mountain Dog ",
        "Bichon Frise",
        "Biewer Terrier",
        "Bloodhound",
        "Boerboel",
        "Bolognese",
        "Border Collie",
        "Border Terrier",
        "Borderdoodle",
        "Borzoi",
        "Boston Terrier",
        "Bouvier Des Flandres ",
        "Boxador",
        "Boxer",
        "Bracco Italiano",
        "Braque D'auvergne",
        "Briard",
        "Brittany Spaniel",
        "Bullmastiff",
        "Cairn Terrier",
        "Canaan Dog",
        "Canadian Eskimo Dog",
        "Cane Corso ",
        "Catalan Sheepdog ",
        "Caucasian Shepherd Dog ",
        "Cavachon",
        "Cavalier King Charles Spaniel",
        "Cavapoo",
        "Central Asian Shepherd",
        "Cesky Terrier",
        "Chesapeake Bay Retriever",
        "Chihuahua",
        "Chinese Crested Dog",
        "Chipoo",
        "Chorkie",
        "Chow Chow",
        "Chug",
        "Clumber Spaniel",
        "Cock-a-chon",
        "Cockapoo",
        "Cocker Jack",
        "Cocker Spaniel",
        "Coonhound",
        "Coton De Tulear",
        "Curly Coated Retriever",
        "Dachshund",
        "Dalmatian ",
        "Dandie Dinmont Terrier",
        "Deerhound",
        "Dobermann",
        "Dogue De Bordeaux ",
        "Dorset Old Tyme Bulldogge ",
        "English Bull Terrier",
        "English Bulldog",
        "English Setter",
        "English Springer Spaniel",
        "English Toy Terrier",
        "Entlebucher Mountain Dog",
        "Estrela Mountain Dog",
        "Eurasier",
        "Field Spaniel",
        "Finnish Lapphund",
        "Finnish Spitz",
        "Flat Coated Retriever",
        "Fox Terrier",
        "Foxhound",
        "French Bulldog",
        "German Longhaired Pointer",
        "German Shepherd",
        "German Shorthaired Pointer",
        "German Spitz ",
        "German Wirehaired Pointer",
        "Giant Schnauzer",
        "Glen Of Imaal Terrier",
        "Goldador",
        "Golden Retriever ",
        "Goldendoodle",
        "Gordon Setter",
        "Grand Bleu De Gascogne",
        "Great Dane",
        "Greater Swiss Mountain Dog",
        "Greenland Dog",
        "Greyhound",
        "Griffon Bruxellois ",
        "Hamiltonstovare ",
        "Harrier",
        "Havanese",
        "Hovawart",
        "Hungarian Puli",
        "Hungarian Pumi",
        "Hungarian Vizsla",
        "Huntaway",
        "Huskamute",
        "Huskita ",
        "Ibizan Hound",
        "Irish Setter",
        "Irish Terrier",
        "Irish Water Spaniel ",
        "Irish Wolfhound",
        "Italian Greyhound ",
        "Italian Spinone",
        "Jack Russell",
        "Jack Tzu",
        "Jackachon",
        "Jackapoo ",
        "Jackawawa",
        "Jagdterrier",
        "Japanese Akita ",
        "Japanese Chin",
        "Japanese Spitze",
        "Jug",
        "Keeshond",
        "Kerry Blue Terrier",
        "King Charles Spaniel",
        "Komondor",
        "Kooikerhondje",
        "Korthals Griffon",
        "Kromfohrlander",
        "Labradinger",
        "Labradoodle",
        "Labrador Retriever",
        "Lagotto Romagnolo",
        "Lakeland Terrier",
        "Lancashire Heeler",
        "Large Munsterlander",
        "Leonberger",
        "Lhasa Apso",
        "Lhasapoo",
        "Lowchen",
        "Lurcher",
        "Malshi",
        "Maltese",
        "Maltipoo",
        "Manchester Terrier",
        "Maremma Sheepdog",
        "Mastiff",
        "Mexican Hairless",
        "Miniature Dachshund",
        "Miniature Pinscher",
        "Miniature Poodle",
        "Miniature Schnauzer",
        "Mixed Breed ",
        "Morkie",
        "Neapolitan Mastiff",
        "Newfoundland",
        "Norfolk Terrier",
        "Northern Inuit",
        "Norwegian Elkhound",
        "Norwich Terrier",
        "Nova Scotia Duck Tolling Retriever",
        "Old English Sheepdog",
        "Otterhound",
        "Papillon",
        "Parson Russell Terrier",
        "Patterdale Terrier",
        "Patterjack",
        "Pekingese",
        "Pharaoh Hound",
        "Picardy Spaniel",
        "Pinscher",
        "Plummer Terrier",
        "Pointer",
        "Polish Lowland Sheepdog",
        "Pomchi",
        "Pomeranian",
        "Pomskie",
        "Poochon",
        "Poodle",
        "Portuguese Podengo",
        "Portuguese Sheepdog",
        "Portuguese Water Dog",
        "Presa Canario",
        "Pugalier",
        "Pugapoo",
        "Puggles",
        "Pug",
        "Pugzu",
        "Pyrenean Mastiff",
        "Pyrenean Mountain Dog ",
        "Pyrenean Sheepdog",
        "Rhodesian Ridgeback",
        "Romanian Mioritic Shepherd",
        "Rottweiler",
        "Rough Collie",
        "Russian Black Terrier",
        "Russian Toy Terrier",
        "Saarloos Wolfdog",
        "Saint Bernard",
        "Salukis ",
        "Samoyed",
        "Schipperke",
        "Schnauzer",
        "Schnoodle",
        "Scottish Terrier",
        "Sealyham Terrier",
        "Shar Pei",
        "Shepadoodle",
        "Shetland Sheepdog",
        "Shiba Inu",
        "Shih Tzu",
        "Shihchon",
        "Shihpoo",
        "Shorkie",
        "Siberian Huskie",
        "Skye Terrier",
        "Sloughi",
        "Smooth Collie ",
        "Soft Coated Wheaten Terrier",
        "Spanador",
        "Spanish Mastiff",
        "Spanish Water Dog",
        "Sporting Lucas Terrier",
        "Springador",
        "Sprocker",
        "Sprollie",
        "Sproodle",
        "Staffordshire Bull Terrier",
        "Sussex Spaniel",
        "Swedish Lapphund",
        "Swedish Vallhund",
        "Tamaskan",
        "Tibetan Mastiff",
        "Tibetan Spaniel",
        "Tibetan Terrier",
        "Toy Poodle",
        "Turkish Kangal",
        "Utonagan",
        "Weimaraner",
        "Welsh Collie ",
        "Welsh Corgi Cardigan",
        "Welsh Corgi Pembroke",
        "Welsh Sheepdog ",
        "Welsh Springer Spaniel",
        "Welsh Terrier",
        "West Highland Terrier",
        "Westiepoo",
        "Wheaten Terrier",
        "Whippet",
        "White Swiss Shepherd ",
        "Yorkie Russell",
        "Yorkshire Terrier",
        "Other Breed",
      ],
      age: [
        "Newborn: 0-2 months",
        "Puppy: 2-6 months",
        "Young: 6-12 months",
        "Adolescent: 1-2 years",
        "Adult: 2-6 years",
        "Fully grown: 7 years",
        "Mature Adult: 7-10 years",
        "Senior: 10 years and older",
      ],
      gender: ["Male", "Female", "Pair", "Unsexed or Unknown", "Mixed"],
      vaccinations: [
        "Fully Vaccinated",
        "Up-to-Date",
        "Non-Core Vaccinations",
        "Rabies Vaccinated",
        "Titers Tested",
        "Medical Exemption",
        "No Vaccinations",
        "Needs Vaccinations",
      ],
    },
    cats: {
      breed: [
        "Abyssinian",
        "Aegen",
        "American Bobtail",
        "American Curl",
        "American Shorthair",
        "American Wirehair",
        "Arabian Mau",
        "Arctic Curl",
        "Asian",
        "Australian Mist",
        "Balinese",
        "Bambino",
        "Bengal",
        "Birman",
        "Bombay",
        "Bramble",
        "British Longhair",
        "British Shorthair",
        "Burmese",
        "Burmilla",
        "Chantilly Tiffany",
        "Chartreux",
        "Chausie",
        "Colorpoint Shorthair",
        "Cornish Rex",
        "Devon Rex",
        "Donskoy",
        "Dwelf",
        "Egyptian Maus",
        "European Shorthair",
        "Exotic",
        "Havana Brown",
        "Highlander",
        "Himalayan",
        "Japanese Bobtail",
        "Keetso",
        "Khao Manee",
        "Korat",
        "Korean Bobtail",
        "Kurillian Bobtail",
        "Laperm",
        "Lykoi",
        "Maine Coon",
        "Manx",
        "Minskin",
        "Mixed Breed",
        "Munchkin",
        "Nebelung",
        "Norwegian Forest Cat",
        "Ocicat",
        "Ojos Azules",
        "Oriental Bicolor",
        "Persian",
        "Peterbald",
        "Pixie Bob",
        "Ragamuffin",
        "Ragdoll",
        "Russian Black",
        "Russian Blue",
        "Russian White",
        "Savannah",
        "Scottish Fold",
        "Selkirk Rex",
        "Serengeti",
        "Siamese",
        "Siberian",
        "Singapura",
        "Snowshoe",
        "Sokoke",
        "Somali",
        "Sphynx",
        "Thai",
        "Tibetans",
        "Tiffany",
        "Tonkinese",
        "Toybob",
        "Toyger",
        "Turkish Angora",
        "Turkish Van",
        "Other Breed",
      ],
      age: [
        "Kitten (0-6 months)",
        "Young Adult (6 months - 2 years)",
        "Adult (2 years - 7 years)",
        "Mature Adult (7 years - 10 years)",
        "Senior (10 years - 14 years)",
        "Geriatric (14 years and older)",
      ],
      gender: ["Male", "Female", "Pair", "Unsexed or Unknown", "Mixed"],
      vaccinations: [
        "Fully Vaccinated",
        "Up-to-Date",
        "Non-Core Vaccinations",
        "Rabies Vaccinated",
        "Titers Tested",
        "Medical Exemption",
        "No Vaccinations",
        "Needs Vaccinations",
      ],
    },
    birds: {
      breed: [
        "Budgie",
        "Caique",
        "Canary",
        "Cockatiel",
        "Doves",
        "Finch",
        "Love Bird ",
        "Parrot ",
        "Pigeon",
        "Pionus ",
        "Rosella",
        "Quail",
        "Partridge",
        "Mynah Bird",
        "Toucan",
        "Lorikeet",
        "Eagle",
        "Hawk",
        "Falcon",
        "Owl",
        "Vulture",
        "Kite",
        "Osprey",
        "Osprey",
        "Buzzard",
        "Other Bird",
      ],
      age: ["Baby", "Juvenile", "Young Adult", "Adult", "Senior"],
      gender: ["Male", "Female", "Pair", "Unsexed or Unknown", "Mixed"],
    },
    fish: {
      species: [
        "Ancistrus ",
        "Archerfish",
        "Arowana",
        "Angel Fish ",
        "Barb ",
        "Betta",
        "Cichlid ",
        "Cardinalfish",
        "Clown Fish ",
        "Discus",
        "Danio",
        "Doctor Fish",
        "Dragon Fish ",
        "Damselfish",
        "Eel",
        "Flowerhorn",
        "Goldfish ",
        "Gouramis",
        "Guppy",
        "Invertibrate Fish ",
        "Koi ",
        "Lake Malawi ",
        "Lionfish",
        "Loach",
        "Marine Fish ",
        "Mandarinfish",
        "Mono",
        "Molly",
        "Neon Tetra ",
        "Oscar",
        "Peacock Cichlid",
        "Pink Kisser",
        "Pipefish",
        "Piranha",
        "Platy",
        "Plecostomus ",
        "Puffer",
        "Rainbow Fish ",
        "Rasbora",
        "Shark ",
        "Scat",
        "Swordtail",
        "Seahorse",
        "Tetra ",
        "Triggerfish",
        "Tropical Fish ",
        "Wild Fish ",
        "Other Fish",
      ],
      tankSize: ["Small tank", "Medium tank", "Large tank"],
      careLevel: ["Beginner", "Intermediate", "Advanced"],
      diet: ["Herbivore", "Carnivore", "Omnivore"],
    },
    reptiles: {
      species: [
        "Lizard",
        "Snake",
        "Terrapin",
        "Tortoise",
        "Turtle",
        "Crocodilian",
        "Other Reptile",
      ],
      age: ["Baby", "Juvenile", "Young Adult", "Adult", "Senior"],
      gender: ["Male", "Female", "Pair", "Unsexed or Unknown", "Mixed"],
      size: ["Small", "Medium", "Large"],
    },
    rabbits: {
      breed: [
        "Alaska",
        "Angora",
        "Argente",
        "Beige",
        "Belgian Hare",
        "Beveren",
        "Blanc De Bouscat",
        "Blanc De Hotots",
        "Blanc De Termonde",
        "Blue Of Sint-niklaas",
        "Britannia Petite",
        "British Giant",
        "Californian",
        "Cashmere Lop",
        "Chinchilla",
        "Continental Giant",
        "Deilenaar",
        "Dutch Tri-coloured",
        "Dutch",
        "Dwarf Hotot",
        "Dwarf Lop",
        "English",
        "English Lop",
        "English Spot",
        "Fauve De Bourgogne",
        "Flemish",
        "French Lop",
        "German Lop",
        "Giant Lop",
        "Giant Papillon",
        "Golden Glavcot",
        "Harlequin",
        "Havana",
        "Himalayan",
        "Holland Lop",
        "Hulstlander",
        "Lilac",
        "Lionhead",
        "Meissener Lop",
        "Mini Lion Lop",
        "Mini Lop",
        "Mini Papillon",
        "Mini Rex",
        "Mixed Breed",
        "Netherland Dwarf",
        "New Zealand",
        "Perlfee",
        "Pointed Beveren",
        "Polish",
        "Rex",
        "Rhinelander",
        "Sable",
        "Sallander",
        "Satin",
        "Schwarzgrannen",
        "Siberian",
        "Silver Fox",
        "Silver",
        "Smoke Pearl",
        "Squirrel",
        "Standard Rex",
        "Sussex",
        "Swiss Fox",
        "Tan",
        "Thrianta",
        "Thuringer",
        "Tri Coloured Dutch",
        "Vienna",
        "Wheaten",
        "Other Rabbit",
      ],
      age: ["Baby", "Juvenile", "Young Adult", "Adult", "Senior"],
      gender: ["Male", "Female", "Pair", "Unsexed or Unknown", "Mixed"],
      vaccinations: [
        "Fully Vaccinated",
        "Up-to-Date",
        "Non-Core Vaccinations",
        "Rabies Vaccinated",
        "Titers Tested",
        "Medical Exemption",
        "No Vaccinations",
        "Needs Vaccinations",
      ],
    },
    rodents: {
      species: [
        "Guinea Pig",
        "Hamster",
        "Mouse",
        "Rat",
        "Chinchilla",
        "Degu",
        "Squirrel",
        "Prairie Dog",
        "Capybara",
        "Ferret",
        "Gerbil",
        "Mixed Breed",
        "Pygmy Hedgehog",
        "Sugar Glider",
        "Viscacha",
        "Mink",
        "Gerbil",
        "Civet",
        "Other Rodent",
      ],
      age: ["Baby", "Juvenile", "Young Adult", "Adult", "Senior"],
      gender: ["Male", "Female", "Pair", "Unsexed or Unknown", "Mixed"],
    },
    livestocks: {
      type: [
        "Alpaca",
        "Animal Feed",
        "Chicken",
        "Cow",
        "Duck",
        "Goose",
        "Goat",
        "Guinea Fowl",
        "Peacock",
        "Pheasant",
        "Pig",
        "Quails",
        "Ram",
        "Sheep",
        "Turkeys",
        "Other Livestock",
      ],
      age: ["Baby", "Juvenile", "Young Adult", "Adult", "Senior"],
      gender: ["Male", "Female", "Pair", "Unsexed or Unknown", "Mixed"],
    },
    horses: {
      breed: [
        "Abaga",
        "Abyssinian",
        "Adaev",
        "Aegidienberger",
        "Akhal-Teke",
        "Albanian",
        "Altai",
        "Alter Real",
        "American Bashkir Curly",
        "American Belgian Draft",
        "American Cream Draft",
        "American Indian Horse",
        "American Paint Horse",
        "American Quarter Horse",
        "American Saddlebred",
        "American Warmblood",
        "Andalusian",
        "Andravida",
        "Anglo-Arabian",
        "Anglo-Kabarda",
        "Appaloosa",
        "Arabian",
        "Ardennais",
        "Arenberg-Nordkirchen",
        "Asturcón",
        "Australian Draught",
        "Australian Stock Horse",
        "Austrian Warmblood",
        "Auvergne",
        "Auxois",
        "Axios",
        "Azerbaijan",
        "Azteca",
        "Baise horse",
        "Bale",
        "Balearic horse",
        "Balikun horse",
        "Baluchi horse",
        "Banker horse",
        "Barb horse",
        "Bardigiano",
        "Bashkir horse",
        "Basque Mountain Horse",
        "Bavarian Warmblood",
        "Belgian Draught",
        "Belgian Sport Horse",
        "Belgian Trotter",
        "Belgian Warmblood",
        "Bhutia Horse",
        "Black Forest Horse ",
        "Blazer horse",
        "Boerperd",
        "Borana",
        "Bosnian Mountain Horse",
        "Boulonnais horse",
        "Brandenburger",
        "Brazilian Sport Horse ",
        "Breton horse",
        "British Warmblood",
        "Brumby",
        "Budyonny horse",
        "Burguete horse",
        "Burmese Horse",
        "Byelorussian Harness Horse",
        "Calabrese horse",
        "Camargue horse",
        "Camarillo White Horse",
        "Campeiro",
        "Campolina",
        "Canadian horse",
        "Canadian Pacer",
        "Carolina Marsh Tacky",
        "Carthusian Spanish horse",
        "Caspian horse",
        "Castilian",
        "Castillonnais",
        "Catria horse",
        "Cavallo Romano della Maremma Laziale",
        "Cerbat Mustang",
        "Chickasaw Horse",
        "Chaidamu horse",
        "Chernomor horse",
        "Chilean horse ",
        "Chinese Mongolian horse",
        "Choctaw horse",
        "Cleveland Bay",
        "Clydesdale horse",
        "Colorado Ranger",
        "Coldblood trotter",
        "Comtois horse",
        "Corsican horse",
        "Costa Rican Saddle Horse",
        "Cretan horse",
        "Criollo horse",
        "Croatian Coldblood",
        "Cuban Criollo",
        "Cumberland Island horse",
        "Czech Warmblood",
        "Daliboz",
        "Danish Warmblood",
        "Danube Delta horse",
        "Dareshuri",
        "Datong horse",
        "Dole Gudbrandsdal",
        "Don",
        "Dongola horse",
        "Draft Trotter",
        "Dutch Harness Horse",
        "Dutch Heavy Draft",
        "Dutch Warmblood",
        "Dzungarian horse",
        "East Bulgarian",
        "Estonian Draft",
        "Estonian Native",
        "Ethiopian horses",
        "Falabella",
        "Faroese ",
        "Finnhorse",
        "Flemish Horse",
        "Fleuve",
        "Fjord horse",
        "Florida Cracker Horse",
        "Foutanké or Fouta",
        "Frederiksborger",
        "Freiberger",
        "French Trotter",
        "Friesian",
        "Furioso-North Star",
        "Galiceno or Galiceño",
        "Galician Pony ",
        "Gelderland horse",
        "Giara Horse",
        "Gidran",
        "Groningen Horse",
        "Hackney horse",
        "Haflinger",
        "Hanoverian horse",
        "Heck horse",
        "Heihe horse",
        "Henson horse",
        "Hequ horse",
        "Hirzai",
        "Hispano-Bretón",
        "Hispano-Árabe ",
        "Holsteiner",
        "Horro",
        "Hungarian Warmblood",
        "Icelandic horse",
        "Indian Country-bred",
        "Iomud",
        "Irish Draught",
        "Irish Sport Horse ",
        "Italian Heavy Draft",
        "Italian Trotter",
        "Jaca Navarra",
        "Jeju horse",
        "Jutland horse",
        "Kabarda horse",
        "Kafa",
        "Kaimanawa horses",
        "Kalmyk horse",
        "Karabair",
        "Karabakh horse ",
        "Karossier ",
        "Karachai horse",
        "Kathiawari horse",
        "Kazakh Horse",
        "Kentucky Mountain Saddle Horse",
        "Kiger Mustang",
        "Kinsky horse",
        "Koheilan",
        "Konik",
        "Kyrgyz Horse",
        "Kisber Felver",
        "Kiso Horse",
        "Kladruber",
        "Knabstrupper",
        "Kundudo horse",
        "Kustanair",
        "Latvian horse",
        "Lipizzan ",
        "Lithuanian Heavy Draught",
        "Ljutomer Trotter",
        "Lokai",
        "Losino horse",
        "Lusitano",
        "Luxembourg Warmblood",
        "Lyngshest",
        "M'Bayar",
        "M'Par",
        "Malopolski",
        "Mallorquín",
        "Mangalarga",
        "Mangalarga Marchador",
        "Maremmano",
        "Marismeño",
        "Marsh Tacky",
        "Marwari horse",
        "Mecklenburger",
        "Međimurje horse",
        "Menorquín horse",
        "Mérens horse",
        "Messara horse",
        "Mezőhegyesi sport-horse ",
        "Mezőhegyes felver",
        "Metis Trotter",
        "Miquelon horse",
        "Miniature horse",
        "Misaki horse",
        "Missouri Fox Trotter",
        "Monchino",
        "Mongolian Horse",
        "Mongolian Wild Horse",
        "Monterufolino",
        "Morab",
        "Morgan horse",
        "Mountain Pleasure Horse",
        "Moyle horse",
        "Muraközi, Murakoz",
        "Murgese",
        "Mustang",
        "Namib Desert Horse",
        "Nangchen horse",
        "National Show Horse",
        "New Altai",
        "Nez Perce Horse",
        "Nivernais horse",
        "Nokota horse",
        "Noma horse",
        "Nonius horse",
        "Nooitgedachter",
        "Nordlandshest",
        "Noriker horse ",
        "Norman Cob",
        "Norsk Kaldblodstraver ",
        "North American Single-footing Horse",
        "North Swedish horse",
        "Novoolexandrian Draught",
        "Novokirghiz",
        "Oberlander Horse",
        "Ogaden",
        "Oldenburger",
        "Orlov Trotter",
        "Ostfriesen ",
        "Paint",
        "Pampa horse",
        "Paso Fino",
        "Pentro horse",
        "Percheron",
        "Persano horse",
        "Peruvian Paso",
        "Pintabian",
        "Pleven horse",
        "Poitevin horse a",
        "Polish Arabian",
        "Posavac",
        "Pottok",
        "Priob",
        "Pryor Mountain Mustang",
        "Przewalski's horse",
        "Pura Raza Española ",
        "Purosangue Orientale",
        "Qatgani",
        "Quarab",
        "Quarter Horse",
        "Racking horse",
        "Retuerta horse",
        "Rhenish German Coldblood ",
        "Rhinelander horse",
        "Riwoche horse",
        "Rocky Mountain Horse",
        "Romanian Sporthorse",
        "Rottaler",
        "Russian Don",
        "Russian Heavy Draft",
        "Russian Trotter",
        "Saddlebred",
        "Salernitano",
        "Samolaco horse",
        "Sanfratellano",
        "Santa Cruz Island horse",
        "Sarcidano horse",
        "Sardinian Anglo-Arab",
        "Schleswig Coldblood",
        "Schwarzwälder Kaltblut",
        "Selale",
        "Sella Italiano",
        "Selle Français",
        "Senner",
        "Shagya Arabian",
        "Shan Horse or Shan Myinn",
        "Shire horse",
        "Siciliano indigeno",
        "Silesian horse",
        "Sindhi horse",
        "Slovenian Cold-blood",
        "Sorraia",
        "Sokolski horse",
        "South German Coldblood ",
        "Soviet Heavy Draft",
        "Spanish Barb",
        "Spanish Jennet Horse",
        "Spanish Mustang",
        "Spanish Tarpan",
        "Spanish Trotter ",
        "Spiti Horse",
        "Spotted Saddle Horse",
        "Standardbred",
        "Suffolk Punch",
        "Svensk Kallblodstravare ",
        "Swedish Ardennes",
        "Swedish Warmblood",
        "Swiss Warmblood",
        "Taishū horse",
        "Takhi",
        "Tawleed",
        "Tchernomor",
        "Tennessee Walking Horse",
        "Tersk horse",
        "Thoroughbred",
        "Tiger Horse",
        "Tokara horse",
        "Tolfetano",
        "Tori horse",
        "Trait Du Nord",
        "Trakehner",
        "Tsushima",
        "Tuigpaard",
        "Tushetian horse",
        "Tuva horse",
        "Ukrainian Riding Horse",
        "Unmol Horse",
        "Uzunyayla",
        "Ventasso horse ",
        "Virginia highlander",
        "Vlaamperd",
        "Vladimir Heavy Draft",
        "Vyatka horse",
        "Waler or Australian Waler",
        "Walkaloosa",
        "Warlander",
        "Welsh Cob ",
        "Westphalian horse",
        "Wielkopolski",
        "Württemberger",
        "Xilingol horse",
        "Yakutian horse",
        "Yili horse",
        "Yonaguni horse",
        "Zangersheide",
        "Zaniskari",
        "Zakynthos horse",
        "Zweibrücker",
        "Žemaitukas ",
        "Zhumd",
        "American Shetland Pony",
        "American Walking Pony",
        "Anadolu Pony",
        "Assateague",
        "Australian Pony",
        "Australian Riding Pony",
        "Bali Pony",
        "Basuto pony",
        "Batak Pony",
        "Bhirum pony",
        "Bosnian Pony",
        "British Spotted Pony",
        "Burmese pony",
        "Camargue horse ",
        "Canadian rustic pony",
        "Carpathian Pony",
        "Caspian horse ",
        "Chincoteague Pony",
        "Chinese Guoxia",
        "Coffin Bay Pony",
        "Connemara pony",
        "Czechoslovakian Small Riding Pony",
        "Dales Pony",
        "Danish Sport Pony",
        "Dartmoor pony",
        "Deli pony",
        "Dülmen Pony",
        "Eriskay pony",
        "Esperia Pony",
        "Exmoor pony",
        "Falabella ",
        "Faroe pony",
        "Fell Pony",
        "Flores pony",
        "French Saddle Pony",
        "Galician Pony",
        "Garrano",
        "Gayoe",
        "German Riding Pony",
        "German Classic Pony",
        "Gotland Pony",
        "Guizhou pony",
        "Gǔo-xìa pony",
        "Hackney pony",
        "Haflinger ",
        "Highland pony",
        "Hokkaido Pony",
        "Hucul Pony ",
        "Icelandic horse ",
        "Java Pony",
        "Karelian pony",
        "Kerry bog pony",
        "Lac La Croix Indian Pony",
        "Landais Pony",
        "Lijiang pony",
        "Lundy Pony",
        "Manipuri Pony",
        "Merens Pony ",
        "Miniature horse",
        "Miyako Pony",
        "Namaqua Pony",
        "Narym Pony",
        "New Forest pony",
        "Newfoundland pony",
        "Peneia Pony",
        "Petiso Argentino",
        "Pindos Pony",
        "Poney Mousseye",
        "Pony of the Americas",
        "Quarter pony",
        "Sable Island Pony",
        "Sandalwood Pony",
        "Shetland pony",
        "Skyros Pony",
        "Sumba and Sumbawa Pony",
        "Tibetan Pony",
        "Timor Pony",
        "Welara",
        "Welsh Pony ",
        "Western Sudan pony",
        "Other Breed",
      ],
      age: ["Baby", "Juvenile", "Young Adult", "Adult", "Senior"],
      gender: ["Stallion", "Mares", "Gelding"],
      trainingLevel: [
        "Untrained",
        "Halter-broken",
        "Broke to ride",
        "Competition ready",
        "Basic Training",
        "Intermediate Training",
        "Advanced Training",
        "Professional Training",
        "Kid/Begginer Friendly",
        "Kid/Begginer Friendly",
        "Schoolmaster",
        "Trail Riding",
      ],
      vaccinations: [
        "Fully Vaccinated",
        "Up-to-Date on Boosters",
        "Vaccination Records Available",
        "Needs Vaccinations",
      ],
      health: [
        "Veterinary Health Certificate",
        "Pre-Purchase Exam Passed",
        "No Known Health Issues",
        "Special Care Needs",
      ],
      hoofCare: [
        "Regularly Trimmed",
        "Hoof Care Records Available",
        "Not Regularly Trimmed",
      ],
      insurance: ["Insured", "Eligible for Insurance"],
    },
    amphibian: {
      species: [
        "Frog",
        "Toad",
        "Salamander  & Newt",
        "Caecilian",
        "Other Species",
      ],
      age: ["Baby", "Juvenile", "Young Adult", "Adult", "Senior"],
      gender: ["Male", "Female", "Pair", "Unsexed or Unknown", "Mixed"],
    },
    SellerRating: ["5*", "4*", "3*", "2*", "1*"],
    SearchWithin: [
      "Nationwide",
      "Current location",
      "Within 1 mile",
      "Within 5 miles",
      "Within 15 miles",
      "Within 30 miles",
      "Within 50 miles",
      "Within 100 miles",
      "Within 200 miles",
    ],
    supplies: {
      type: [
        "Dogs",
        "Cats",
        "Birds",
        "Fish",
        "Reptile",
        "Rabbits",
        "Rodents",
        "Livestock",
        "Horses",
        "Amphibian",
        "Other Pet",
      ],
    },
  },
};
