export const selectData = {
  mealType: [
    "Not Listed",
    "Breakfast",
    "Lunch",
    "Dinner",
    "Snacks",
    "Desserts",
    "Appetizers/Starters",
    "Brunch",
    "Side Dishes",
    "Beverages",
    "Late Night",
    "Holiday/Special Occasion",
    "Street Food",
    "Vegan/Vegetarian",
    "Kids' Meals",
    "Health-Conscious",
  ],
  dietaryPreferences: [
    "Not Specified",
    "Vegetarian",
    "Vegan",
    "Pescatarian",
    "Gluten-Free",
    "Lactose-Free",
    "Keto",
    "Paleo",
    "Whole30",
    "Low-Carb",
    "DASH Diet",
    "Mediterranean Diet",
    "Halal",
    "Kosher",
    "Diabetic-Friendly",
    "Low-FODMAP",
    "Plant-Based",
    "Allergen-Free",
    "Raw Food Diet",
    "AIP (Autoimmune Protocol)",
    "Flexitarian",
  ],
  searchWithin: [
    "Nationwide",
    "Current location",
    "Within 1 mile",
    "Within 5 miles",
    "Within 15 miles",
    "Within 30 miles",
    "Within 50 miles",
    "Within 100 miles",
    "Within 200 miles",
  ],
  deliveryOptions: [
    "Not Specified",
    "Local Pickup",
    "Standard Shipping",
    "Expedited Shipping",
    "Free Shipping",
    "Flat Rate Shipping",
    "International Shipping",
    "Temperature-Controlled Shipping",
    "Insured Shipping",
    "Tracking Included",
    "Same-Day Delivery",
    "Scheduled Delivery",
    "No Shipping (Digital Delivery)",
    "Curbside Delivery",
    "Drone Delivery",
  ],
  sellerRating: ["5*", "4*", "3*", "2*", "1*", "0*"],
};
